# Auto-generated for SageMath — Structure 4
# All variables in b_X_Y_Z form (no tau symbols).
# Parameters: []
# Unknowns:   ['b', 'b_Tm_E_Tm', 'b_Tm_E_Tp', 'b_Tm_F_Tm', 'b_Tm_F_Tp', 'b_Tm_H_Tm', 'b_Tm_H_Tp', 'b_Tm_Tp_E', 'b_Tm_Tp_F', 'b_Tm_Tp_H', 'b_Tp_E_Tm', 'b_Tp_E_Tp', 'b_Tp_F_Tm', 'b_Tp_F_Tp', 'b_Tp_H_Tm', 'b_Tp_H_Tp']

var_names = ['b', 'b_Tm_E_Tm', 'b_Tm_E_Tp', 'b_Tm_F_Tm', 'b_Tm_F_Tp', 'b_Tm_H_Tm', 'b_Tm_H_Tp', 'b_Tm_Tp_E', 'b_Tm_Tp_F', 'b_Tm_Tp_H', 'b_Tp_E_Tm', 'b_Tp_E_Tp', 'b_Tp_F_Tm', 'b_Tp_F_Tp', 'b_Tp_H_Tm', 'b_Tp_H_Tp']

polys_raw = [
    '-b_Tm_E_Tp*b_Tp_F_Tm + b_Tm_E_Tp + b_Tm_F_Tp*b_Tp_E_Tm + b_Tp_F_Tm + b_Tp_H_Tp',
    '-b_Tm_E_Tm*b_Tp_F_Tm + b_Tm_E_Tm + b_Tm_F_Tm*b_Tp_E_Tm - b_Tp_E_Tm*b_Tp_F_Tp + b_Tp_E_Tp*b_Tp_F_Tm - b_Tp_E_Tp + b_Tp_H_Tm',
    'b_Tm_E_Tm*b_Tm_F_Tp - b_Tm_E_Tp*b_Tm_F_Tm + b_Tm_E_Tp*b_Tp_F_Tp + b_Tm_F_Tm - b_Tm_F_Tp*b_Tp_E_Tp + b_Tm_H_Tp - b_Tp_F_Tp',
    'b_Tm_E_Tp*b_Tp_F_Tm - b_Tm_E_Tp - b_Tm_F_Tp*b_Tp_E_Tm + b_Tm_H_Tm - b_Tp_F_Tm',
    '-b_Tm_E_Tp*b_Tp_H_Tm + b_Tm_H_Tp*b_Tp_E_Tm + b_Tp_E_Tp + b_Tp_H_Tm',
    '-b_Tm_E_Tm*b_Tp_H_Tm + b_Tm_H_Tm*b_Tp_E_Tm - b_Tp_E_Tm*b_Tp_H_Tp - b_Tp_E_Tm + b_Tp_E_Tp*b_Tp_H_Tm',
    'b_Tm_E_Tm*b_Tm_H_Tp - b_Tm_E_Tp*b_Tm_H_Tm + b_Tm_E_Tp*b_Tp_H_Tp + b_Tm_H_Tm - b_Tm_H_Tp*b_Tp_E_Tp - b_Tp_H_Tp',
    'b_Tm_E_Tm + b_Tm_E_Tp*b_Tp_H_Tm - b_Tm_H_Tp*b_Tp_E_Tm - b_Tp_H_Tm',
    '-b_Tm_E_Tp*b_Tp_E_Tm + b_Tp_E_Tm - b_Tp_E_Tp**2',
    '-b_Tm_E_Tm*b_Tp_E_Tm - b_Tp_E_Tm*b_Tp_E_Tp',
    'b*b_Tp_H_Tp - b_Tm_E_Tp*b_Tp_F_Tm - b_Tp_E_Tp*b_Tp_F_Tp + b_Tp_F_Tm - b_Tp_H_Tp',
    'b*b_Tp_H_Tm - b_Tm_E_Tm*b_Tp_F_Tm - b_Tp_E_Tm*b_Tp_F_Tp - b_Tp_H_Tm',
    'b*b_Tp_E_Tp - b_Tm_E_Tp*b_Tp_H_Tm - b_Tp_E_Tp*b_Tp_H_Tp + b_Tp_H_Tm',
    'b*b_Tp_E_Tm - b_Tm_E_Tm*b_Tp_H_Tm - b_Tp_E_Tm*b_Tp_H_Tp',
    '-b_Tm_Tp_E*b_Tp_E_Tm + b_Tp_E_Tp',
    '-b_Tm_Tp_F*b_Tp_E_Tm',
    '-b_Tm_Tp_H*b_Tp_E_Tm + b_Tp_E_Tm',
    'b*b_Tm_Tp_H - b - b_Tm_E_Tm*b_Tm_Tp_E + b_Tm_E_Tp - 1',
    '-b_Tm_E_Tm*b_Tm_Tp_F',
    'b*b_Tm_Tp_F - b_Tm_E_Tm*b_Tm_Tp_H + b_Tm_E_Tm - b_Tm_Tp_F',
    '-b_Tm_E_Tm*b_Tm_E_Tp + b_Tm_E_Tm - b_Tm_E_Tp*b_Tp_E_Tp - b_Tp_E_Tp',
    '-b_Tm_E_Tm**2 - b_Tm_E_Tp*b_Tp_E_Tm - b_Tp_E_Tm',
    'b*b_Tm_H_Tp - b_Tm_E_Tp*b_Tm_F_Tm + b_Tm_F_Tm - b_Tm_F_Tp*b_Tp_E_Tp - b_Tm_H_Tp - b_Tp_F_Tp',
    'b*b_Tm_H_Tm - b_Tm_E_Tm*b_Tm_F_Tm - b_Tm_F_Tp*b_Tp_E_Tm - b_Tm_H_Tm - b_Tp_F_Tm',
    'b*b_Tm_E_Tp - b_Tm_E_Tp*b_Tm_H_Tm + b_Tm_H_Tm - b_Tm_H_Tp*b_Tp_E_Tp - b_Tp_H_Tp',
    'b*b_Tm_E_Tm - b_Tm_E_Tm*b_Tm_H_Tm - b_Tm_H_Tp*b_Tp_E_Tm - b_Tp_H_Tm',
    '-b*b_Tm_Tp_H + b_Tm_Tp_E*b_Tp_E_Tp - 1',
    'b_Tm_Tp_F*b_Tp_E_Tp - b_Tp_E_Tm',
    '-b*b_Tm_Tp_F + b_Tm_Tp_F + b_Tm_Tp_H*b_Tp_E_Tp',
    'b_Tm_E_Tp*b_Tm_Tp_E',
    '-b_Tm_E_Tm + b_Tm_E_Tp*b_Tm_Tp_F',
    'b + b_Tm_E_Tp*b_Tm_Tp_H + 1',
    'b_Tm_E_Tp*b_Tp_F_Tm - b_Tm_E_Tp - b_Tm_F_Tp*b_Tp_E_Tm - b_Tp_F_Tm - b_Tp_H_Tp',
    'b_Tm_E_Tm*b_Tp_F_Tm - b_Tm_E_Tm - b_Tm_F_Tm*b_Tp_E_Tm + b_Tp_E_Tm*b_Tp_F_Tp - b_Tp_E_Tp*b_Tp_F_Tm + b_Tp_E_Tp - b_Tp_H_Tm',
    '-b_Tm_E_Tm*b_Tm_F_Tp + b_Tm_E_Tp*b_Tm_F_Tm - b_Tm_E_Tp*b_Tp_F_Tp - b_Tm_F_Tm + b_Tm_F_Tp*b_Tp_E_Tp - b_Tm_H_Tp + b_Tp_F_Tp',
    '-b_Tm_E_Tp*b_Tp_F_Tm + b_Tm_E_Tp + b_Tm_F_Tp*b_Tp_E_Tm - b_Tm_H_Tm + b_Tp_F_Tm',
    '-b_Tm_F_Tp*b_Tp_H_Tm + b_Tm_H_Tp*b_Tp_F_Tm - b_Tm_H_Tp - b_Tp_F_Tp',
    '-b_Tm_F_Tm*b_Tp_H_Tm + b_Tm_H_Tm*b_Tp_F_Tm - b_Tm_H_Tm - b_Tp_F_Tm*b_Tp_H_Tp + b_Tp_F_Tp*b_Tp_H_Tm + b_Tp_H_Tp',
    'b_Tm_F_Tm*b_Tm_H_Tp - b_Tm_F_Tp*b_Tm_H_Tm + b_Tm_F_Tp*b_Tp_H_Tp + b_Tm_F_Tp - b_Tm_H_Tp*b_Tp_F_Tp',
    '-b_Tm_F_Tm + b_Tm_F_Tp*b_Tp_H_Tm - b_Tm_H_Tp*b_Tp_F_Tm + b_Tm_H_Tp',
    'b*b_Tp_H_Tp - b_Tm_E_Tp - b_Tm_F_Tp*b_Tp_E_Tm - b_Tp_E_Tp*b_Tp_F_Tp + b_Tp_H_Tp',
    'b*b_Tp_H_Tm - b_Tm_E_Tm - b_Tm_F_Tm*b_Tp_E_Tm - b_Tp_E_Tp*b_Tp_F_Tm + b_Tp_E_Tp + b_Tp_H_Tm',
    '-b_Tm_F_Tp*b_Tp_F_Tm - b_Tm_F_Tp + b_Tp_E_Tp - b_Tp_F_Tp**2',
    '-b_Tm_F_Tm*b_Tp_F_Tm - b_Tm_F_Tm + b_Tp_E_Tm - b_Tp_F_Tm*b_Tp_F_Tp + b_Tp_F_Tp',
    'b*b_Tp_F_Tp - b_Tm_F_Tp*b_Tp_H_Tm - b_Tm_H_Tp - b_Tp_F_Tp*b_Tp_H_Tp',
    'b*b_Tp_F_Tm - b_Tm_F_Tm*b_Tp_H_Tm - b_Tm_H_Tm - b_Tp_F_Tm*b_Tp_H_Tp + b_Tp_H_Tp',
    '-b_Tm_Tp_E*b_Tp_F_Tm + b_Tp_F_Tp',
    '-b_Tm_Tp_F*b_Tp_F_Tm',
    '-b - b_Tm_Tp_H*b_Tp_F_Tm + b_Tp_F_Tm + 1',
    '-b_Tm_F_Tm*b_Tm_Tp_E + b_Tm_F_Tp + b_Tm_Tp_F',
    'b*b_Tm_Tp_H - b - b_Tm_F_Tm*b_Tm_Tp_F + 1',
    'b*b_Tm_Tp_E - b_Tm_F_Tm*b_Tm_Tp_H + b_Tm_F_Tm + b_Tm_Tp_E',
    'b*b_Tm_H_Tp - b_Tm_E_Tm*b_Tm_F_Tp - b_Tm_E_Tp*b_Tp_F_Tp + b_Tm_H_Tp',
    'b*b_Tm_H_Tm - b_Tm_E_Tm*b_Tm_F_Tm - b_Tm_E_Tp*b_Tp_F_Tm + b_Tm_E_Tp + b_Tm_H_Tm',
    'b_Tm_E_Tp - b_Tm_F_Tm*b_Tm_F_Tp - b_Tm_F_Tp*b_Tp_F_Tp',
    'b_Tm_E_Tm - b_Tm_F_Tm**2 - b_Tm_F_Tp*b_Tp_F_Tm + b_Tm_F_Tp',
    'b*b_Tm_F_Tp - b_Tm_F_Tp*b_Tm_H_Tm - b_Tm_H_Tp*b_Tp_F_Tp',
    'b*b_Tm_F_Tm - b_Tm_F_Tm*b_Tm_H_Tm - b_Tm_H_Tp*b_Tp_F_Tm + b_Tm_H_Tp',
    'b_Tm_Tp_E*b_Tp_F_Tp - b_Tm_Tp_F',
    '-b*b_Tm_Tp_H + b_Tm_Tp_F*b_Tp_F_Tp - b_Tp_F_Tm + 1',
    '-b*b_Tm_Tp_E - b_Tm_Tp_E + b_Tm_Tp_H*b_Tp_F_Tp',
    'b_Tm_F_Tp*b_Tm_Tp_E + 1',
    '-b_Tm_F_Tm + b_Tm_F_Tp*b_Tm_Tp_F',
    'b_Tm_F_Tp*b_Tm_Tp_H',
    'b_Tm_E_Tp*b_Tp_H_Tm - b_Tm_H_Tp*b_Tp_E_Tm - b_Tp_E_Tp - b_Tp_H_Tm',
    'b_Tm_E_Tm*b_Tp_H_Tm - b_Tm_H_Tm*b_Tp_E_Tm + b_Tp_E_Tm*b_Tp_H_Tp + b_Tp_E_Tm - b_Tp_E_Tp*b_Tp_H_Tm',
    '-b_Tm_E_Tm*b_Tm_H_Tp + b_Tm_E_Tp*b_Tm_H_Tm - b_Tm_E_Tp*b_Tp_H_Tp - b_Tm_H_Tm + b_Tm_H_Tp*b_Tp_E_Tp + b_Tp_H_Tp',
    '-b_Tm_E_Tm - b_Tm_E_Tp*b_Tp_H_Tm + b_Tm_H_Tp*b_Tp_E_Tm + b_Tp_H_Tm',
    'b_Tm_F_Tp*b_Tp_H_Tm - b_Tm_H_Tp*b_Tp_F_Tm + b_Tm_H_Tp + b_Tp_F_Tp',
    'b_Tm_F_Tm*b_Tp_H_Tm - b_Tm_H_Tm*b_Tp_F_Tm + b_Tm_H_Tm + b_Tp_F_Tm*b_Tp_H_Tp - b_Tp_F_Tp*b_Tp_H_Tm - b_Tp_H_Tp',
    '-b_Tm_F_Tm*b_Tm_H_Tp + b_Tm_F_Tp*b_Tm_H_Tm - b_Tm_F_Tp*b_Tp_H_Tp - b_Tm_F_Tp + b_Tm_H_Tp*b_Tp_F_Tp',
    'b_Tm_F_Tm - b_Tm_F_Tp*b_Tp_H_Tm + b_Tm_H_Tp*b_Tp_F_Tm - b_Tm_H_Tp',
    'b*b_Tp_E_Tp - b_Tm_H_Tp*b_Tp_E_Tm - b_Tp_E_Tp*b_Tp_H_Tp - b_Tp_E_Tp',
    'b*b_Tp_E_Tm - b_Tm_H_Tm*b_Tp_E_Tm + b_Tp_E_Tm - b_Tp_E_Tp*b_Tp_H_Tm',
    'b*b_Tp_F_Tp - b_Tm_H_Tp*b_Tp_F_Tm - b_Tp_F_Tp*b_Tp_H_Tp + b_Tp_F_Tp',
    'b*b_Tp_F_Tm - b_Tm_H_Tm*b_Tp_F_Tm - b_Tp_F_Tp*b_Tp_H_Tm',
    'b*b_Tp_H_Tp - b_Tm_H_Tp*b_Tp_H_Tm - b_Tp_H_Tp**2',
    'b*b_Tp_H_Tm - b_Tm_H_Tm*b_Tp_H_Tm - b_Tp_H_Tm*b_Tp_H_Tp - b_Tp_H_Tm',
    '-b - b_Tm_Tp_E*b_Tp_H_Tm + b_Tp_H_Tp',
    '-b_Tm_Tp_F*b_Tp_H_Tm',
    '-b_Tm_Tp_H*b_Tp_H_Tm + b_Tp_H_Tm',
    'b*b_Tm_Tp_E - b_Tm_H_Tm*b_Tm_Tp_E + b_Tm_H_Tp - b_Tm_Tp_E',
    'b*b_Tm_Tp_F - b_Tm_H_Tm*b_Tm_Tp_F + b_Tm_Tp_F',
    'b*b_Tm_Tp_H - b - b_Tm_H_Tm*b_Tm_Tp_H + b_Tm_H_Tm',
    'b*b_Tm_E_Tp - b_Tm_E_Tm*b_Tm_H_Tp - b_Tm_E_Tp*b_Tp_H_Tp',
    'b*b_Tm_E_Tm - b_Tm_E_Tm*b_Tm_H_Tm - b_Tm_E_Tm - b_Tm_E_Tp*b_Tp_H_Tm',
    'b*b_Tm_F_Tp - b_Tm_F_Tm*b_Tm_H_Tp - b_Tm_F_Tp*b_Tp_H_Tp - b_Tm_F_Tp',
    'b*b_Tm_F_Tm - b_Tm_F_Tm*b_Tm_H_Tm + b_Tm_F_Tm - b_Tm_F_Tp*b_Tp_H_Tm',
    'b*b_Tm_H_Tp - b_Tm_H_Tm*b_Tm_H_Tp - b_Tm_H_Tp*b_Tp_H_Tp + b_Tm_H_Tp',
    'b*b_Tm_H_Tm - b_Tm_H_Tm**2 - b_Tm_H_Tp*b_Tp_H_Tm',
    '-b*b_Tm_Tp_E + b_Tm_Tp_E*b_Tp_H_Tp + b_Tm_Tp_E',
    '-b*b_Tm_Tp_F + b_Tm_Tp_F*b_Tp_H_Tp - b_Tm_Tp_F - b_Tp_H_Tm',
    '-b*b_Tm_Tp_H + b_Tm_Tp_H*b_Tp_H_Tp',
    'b_Tm_H_Tp*b_Tm_Tp_E',
    'b - b_Tm_H_Tm + b_Tm_H_Tp*b_Tm_Tp_F',
    'b_Tm_H_Tp*b_Tm_Tp_H',
    'b_Tm_E_Tp*b_Tp_E_Tm - b_Tp_E_Tm + b_Tp_E_Tp**2',
    'b_Tm_E_Tm*b_Tp_E_Tm + b_Tp_E_Tm*b_Tp_E_Tp',
    '-b*b_Tp_H_Tp + b_Tm_E_Tp*b_Tp_F_Tm + b_Tp_E_Tp*b_Tp_F_Tp - b_Tp_F_Tm + b_Tp_H_Tp',
    '-b*b_Tp_H_Tm + b_Tm_E_Tm*b_Tp_F_Tm + b_Tp_E_Tm*b_Tp_F_Tp + b_Tp_H_Tm',
    '-b*b_Tp_E_Tp + b_Tm_E_Tp*b_Tp_H_Tm + b_Tp_E_Tp*b_Tp_H_Tp - b_Tp_H_Tm',
    '-b*b_Tp_E_Tm + b_Tm_E_Tm*b_Tp_H_Tm + b_Tp_E_Tm*b_Tp_H_Tp',
    'b_Tm_Tp_E*b_Tp_E_Tm - b_Tp_E_Tp',
    'b_Tm_Tp_F*b_Tp_E_Tm',
    'b_Tm_Tp_H*b_Tp_E_Tm - b_Tp_E_Tm',
    '-b*b_Tm_Tp_H + b + b_Tm_E_Tm*b_Tm_Tp_E - b_Tm_E_Tp + 1',
    'b_Tm_E_Tm*b_Tm_Tp_F',
    '-b*b_Tm_Tp_F + b_Tm_E_Tm*b_Tm_Tp_H - b_Tm_E_Tm + b_Tm_Tp_F',
    '-b*b_Tp_H_Tp + b_Tm_E_Tp + b_Tm_F_Tp*b_Tp_E_Tm + b_Tp_E_Tp*b_Tp_F_Tp - b_Tp_H_Tp',
    '-b*b_Tp_H_Tm + b_Tm_E_Tm + b_Tm_F_Tm*b_Tp_E_Tm + b_Tp_E_Tp*b_Tp_F_Tm - b_Tp_E_Tp - b_Tp_H_Tm',
    'b_Tm_F_Tp*b_Tp_F_Tm + b_Tm_F_Tp - b_Tp_E_Tp + b_Tp_F_Tp**2',
    'b_Tm_F_Tm*b_Tp_F_Tm + b_Tm_F_Tm - b_Tp_E_Tm + b_Tp_F_Tm*b_Tp_F_Tp - b_Tp_F_Tp',
    '-b*b_Tp_F_Tp + b_Tm_F_Tp*b_Tp_H_Tm + b_Tm_H_Tp + b_Tp_F_Tp*b_Tp_H_Tp',
    '-b*b_Tp_F_Tm + b_Tm_F_Tm*b_Tp_H_Tm + b_Tm_H_Tm + b_Tp_F_Tm*b_Tp_H_Tp - b_Tp_H_Tp',
    'b_Tm_Tp_E*b_Tp_F_Tm - b_Tp_F_Tp',
    'b_Tm_Tp_F*b_Tp_F_Tm',
    'b + b_Tm_Tp_H*b_Tp_F_Tm - b_Tp_F_Tm - 1',
    'b_Tm_F_Tm*b_Tm_Tp_E - b_Tm_F_Tp - b_Tm_Tp_F',
    '-b*b_Tm_Tp_H + b + b_Tm_F_Tm*b_Tm_Tp_F - 1',
    '-b*b_Tm_Tp_E + b_Tm_F_Tm*b_Tm_Tp_H - b_Tm_F_Tm - b_Tm_Tp_E',
    '-b*b_Tp_E_Tp + b_Tm_H_Tp*b_Tp_E_Tm + b_Tp_E_Tp*b_Tp_H_Tp + b_Tp_E_Tp',
    '-b*b_Tp_E_Tm + b_Tm_H_Tm*b_Tp_E_Tm - b_Tp_E_Tm + b_Tp_E_Tp*b_Tp_H_Tm',
    '-b*b_Tp_F_Tp + b_Tm_H_Tp*b_Tp_F_Tm + b_Tp_F_Tp*b_Tp_H_Tp - b_Tp_F_Tp',
    '-b*b_Tp_F_Tm + b_Tm_H_Tm*b_Tp_F_Tm + b_Tp_F_Tp*b_Tp_H_Tm',
    '-b*b_Tp_H_Tp + b_Tm_H_Tp*b_Tp_H_Tm + b_Tp_H_Tp**2',
    '-b*b_Tp_H_Tm + b_Tm_H_Tm*b_Tp_H_Tm + b_Tp_H_Tm*b_Tp_H_Tp + b_Tp_H_Tm',
    'b + b_Tm_Tp_E*b_Tp_H_Tm - b_Tp_H_Tp',
    'b_Tm_Tp_F*b_Tp_H_Tm',
    'b_Tm_Tp_H*b_Tp_H_Tm - b_Tp_H_Tm',
    '-b*b_Tm_Tp_E + b_Tm_H_Tm*b_Tm_Tp_E - b_Tm_H_Tp + b_Tm_Tp_E',
    '-b*b_Tm_Tp_F + b_Tm_H_Tm*b_Tm_Tp_F - b_Tm_Tp_F',
    '-b*b_Tm_Tp_H + b + b_Tm_H_Tm*b_Tm_Tp_H - b_Tm_H_Tm',
    '-b_Tm_Tp_E*b_Tp_E_Tm + b_Tp_E_Tp',
    '-b_Tm_Tp_F*b_Tp_E_Tm',
    '-b_Tm_Tp_H*b_Tp_E_Tm + b_Tp_E_Tm',
    '-b_Tm_Tp_E*b_Tp_F_Tm + b_Tp_F_Tp',
    '-b_Tm_Tp_F*b_Tp_F_Tm',
    '-b - b_Tm_Tp_H*b_Tp_F_Tm + b_Tp_F_Tm + 1',
    '-b - b_Tm_Tp_E*b_Tp_H_Tm + b_Tp_H_Tp',
    '-b_Tm_Tp_F*b_Tp_H_Tm',
    '-b_Tm_Tp_H*b_Tp_H_Tm + b_Tp_H_Tm',
    '-b_Tm_E_Tp - b_Tm_Tp_E*b_Tp_E_Tp - b_Tm_Tp_F*b_Tp_F_Tp - b_Tm_Tp_H*b_Tp_H_Tp + b_Tp_H_Tp + 1',
    '-b_Tm_E_Tm - b_Tm_Tp_E*b_Tp_E_Tm - b_Tm_Tp_F*b_Tp_F_Tm - b_Tm_Tp_H*b_Tp_H_Tm + b_Tp_H_Tm',
    'b + b_Tm_E_Tm*b_Tm_Tp_E - b_Tm_E_Tp - b_Tm_Tp_E*b_Tp_E_Tp - 1',
    'b_Tm_E_Tm*b_Tm_Tp_F - b_Tm_Tp_F*b_Tp_E_Tp + b_Tp_E_Tm',
    'b_Tm_E_Tm*b_Tm_Tp_H - b_Tm_E_Tm - b_Tm_Tp_H*b_Tp_E_Tp',
    'b_Tm_F_Tm*b_Tm_Tp_E - b_Tm_F_Tp - b_Tm_Tp_E*b_Tp_F_Tp',
    'b + b_Tm_F_Tm*b_Tm_Tp_F - b_Tm_Tp_F*b_Tp_F_Tp + b_Tp_F_Tm + 1',
    'b_Tm_F_Tm*b_Tm_Tp_H - b_Tm_F_Tm - b_Tm_Tp_H*b_Tp_F_Tp',
    'b_Tm_H_Tm*b_Tm_Tp_E - b_Tm_H_Tp - b_Tm_Tp_E*b_Tp_H_Tp',
    'b_Tm_H_Tm*b_Tm_Tp_F - b_Tm_Tp_F*b_Tp_H_Tp + b_Tp_H_Tm',
    'b + b_Tm_H_Tm*b_Tm_Tp_H - b_Tm_H_Tm - b_Tm_Tp_H*b_Tp_H_Tp',
    '-b_Tm_E_Tp - b_Tm_Tp_E*b_Tp_E_Tp - b_Tm_Tp_F*b_Tp_F_Tp - b_Tm_Tp_H*b_Tp_H_Tp + b_Tp_H_Tp + 1',
    '-b_Tm_E_Tm - b_Tm_Tp_E*b_Tp_E_Tm - b_Tm_Tp_F*b_Tp_F_Tm - b_Tm_Tp_H*b_Tp_H_Tm + b_Tp_H_Tm',
    'b_Tm_E_Tp*b_Tm_Tp_E + b_Tm_F_Tp*b_Tm_Tp_F + b_Tm_H_Tp*b_Tm_Tp_H + b_Tp_F_Tp',
    'b_Tm_E_Tm*b_Tm_Tp_E + b_Tm_F_Tm*b_Tm_Tp_F + b_Tm_H_Tm*b_Tm_Tp_H + b_Tp_F_Tm - 1',
    'b_Tm_E_Tm*b_Tm_E_Tp - b_Tm_E_Tm + b_Tm_E_Tp*b_Tp_E_Tp + b_Tp_E_Tp',
    'b_Tm_E_Tm**2 + b_Tm_E_Tp*b_Tp_E_Tm + b_Tp_E_Tm',
    '-b*b_Tm_H_Tp + b_Tm_E_Tp*b_Tm_F_Tm - b_Tm_F_Tm + b_Tm_F_Tp*b_Tp_E_Tp + b_Tm_H_Tp + b_Tp_F_Tp',
    '-b*b_Tm_H_Tm + b_Tm_E_Tm*b_Tm_F_Tm + b_Tm_F_Tp*b_Tp_E_Tm + b_Tm_H_Tm + b_Tp_F_Tm',
    '-b*b_Tm_E_Tp + b_Tm_E_Tp*b_Tm_H_Tm - b_Tm_H_Tm + b_Tm_H_Tp*b_Tp_E_Tp + b_Tp_H_Tp',
    '-b*b_Tm_E_Tm + b_Tm_E_Tm*b_Tm_H_Tm + b_Tm_H_Tp*b_Tp_E_Tm + b_Tp_H_Tm',
    'b*b_Tm_Tp_H - b_Tm_Tp_E*b_Tp_E_Tp + 1',
    '-b_Tm_Tp_F*b_Tp_E_Tp + b_Tp_E_Tm',
    'b*b_Tm_Tp_F - b_Tm_Tp_F - b_Tm_Tp_H*b_Tp_E_Tp',
    '-b_Tm_E_Tp*b_Tm_Tp_E',
    'b_Tm_E_Tm - b_Tm_E_Tp*b_Tm_Tp_F',
    '-b - b_Tm_E_Tp*b_Tm_Tp_H - 1',
    '-b*b_Tm_H_Tp + b_Tm_E_Tm*b_Tm_F_Tp + b_Tm_E_Tp*b_Tp_F_Tp - b_Tm_H_Tp',
    '-b*b_Tm_H_Tm + b_Tm_E_Tm*b_Tm_F_Tm + b_Tm_E_Tp*b_Tp_F_Tm - b_Tm_E_Tp - b_Tm_H_Tm',
    '-b_Tm_E_Tp + b_Tm_F_Tm*b_Tm_F_Tp + b_Tm_F_Tp*b_Tp_F_Tp',
    '-b_Tm_E_Tm + b_Tm_F_Tm**2 + b_Tm_F_Tp*b_Tp_F_Tm - b_Tm_F_Tp',
    '-b*b_Tm_F_Tp + b_Tm_F_Tp*b_Tm_H_Tm + b_Tm_H_Tp*b_Tp_F_Tp',
    '-b*b_Tm_F_Tm + b_Tm_F_Tm*b_Tm_H_Tm + b_Tm_H_Tp*b_Tp_F_Tm - b_Tm_H_Tp',
    '-b_Tm_Tp_E*b_Tp_F_Tp + b_Tm_Tp_F',
    'b*b_Tm_Tp_H - b_Tm_Tp_F*b_Tp_F_Tp + b_Tp_F_Tm - 1',
    'b*b_Tm_Tp_E + b_Tm_Tp_E - b_Tm_Tp_H*b_Tp_F_Tp',
    '-b_Tm_F_Tp*b_Tm_Tp_E - 1',
    'b_Tm_F_Tm - b_Tm_F_Tp*b_Tm_Tp_F',
    '-b_Tm_F_Tp*b_Tm_Tp_H',
    '-b*b_Tm_E_Tp + b_Tm_E_Tm*b_Tm_H_Tp + b_Tm_E_Tp*b_Tp_H_Tp',
    '-b*b_Tm_E_Tm + b_Tm_E_Tm*b_Tm_H_Tm + b_Tm_E_Tm + b_Tm_E_Tp*b_Tp_H_Tm',
    '-b*b_Tm_F_Tp + b_Tm_F_Tm*b_Tm_H_Tp + b_Tm_F_Tp*b_Tp_H_Tp + b_Tm_F_Tp',
    '-b*b_Tm_F_Tm + b_Tm_F_Tm*b_Tm_H_Tm - b_Tm_F_Tm + b_Tm_F_Tp*b_Tp_H_Tm',
    '-b*b_Tm_H_Tp + b_Tm_H_Tm*b_Tm_H_Tp + b_Tm_H_Tp*b_Tp_H_Tp - b_Tm_H_Tp',
    '-b*b_Tm_H_Tm + b_Tm_H_Tm**2 + b_Tm_H_Tp*b_Tp_H_Tm',
    'b*b_Tm_Tp_E - b_Tm_Tp_E*b_Tp_H_Tp - b_Tm_Tp_E',
    'b*b_Tm_Tp_F - b_Tm_Tp_F*b_Tp_H_Tp + b_Tm_Tp_F + b_Tp_H_Tm',
    'b*b_Tm_Tp_H - b_Tm_Tp_H*b_Tp_H_Tp',
    '-b_Tm_H_Tp*b_Tm_Tp_E',
    '-b + b_Tm_H_Tm - b_Tm_H_Tp*b_Tm_Tp_F',
    '-b_Tm_H_Tp*b_Tm_Tp_H',
    'b_Tm_E_Tp*b_Tm_Tp_E',
    '-b_Tm_E_Tm + b_Tm_E_Tp*b_Tm_Tp_F',
    'b + b_Tm_E_Tp*b_Tm_Tp_H + 1',
    'b_Tm_F_Tp*b_Tm_Tp_E + 1',
    '-b_Tm_F_Tm + b_Tm_F_Tp*b_Tm_Tp_F',
    'b_Tm_F_Tp*b_Tm_Tp_H',
    'b_Tm_H_Tp*b_Tm_Tp_E',
    'b - b_Tm_H_Tm + b_Tm_H_Tp*b_Tm_Tp_F',
    'b_Tm_H_Tp*b_Tm_Tp_H',
    'b_Tm_E_Tp*b_Tm_Tp_E + b_Tm_F_Tp*b_Tm_Tp_F + b_Tm_H_Tp*b_Tm_Tp_H + b_Tp_F_Tp',
    'b_Tm_E_Tm*b_Tm_Tp_E + b_Tm_F_Tm*b_Tm_Tp_F + b_Tm_H_Tm*b_Tm_Tp_H + b_Tp_F_Tm - 1',
    'b**2 + 1',
]
