# Auto-generated for SageMath — Structure 2
# All variables in b_X_Y_Z form (no tau symbols).
# Parameters: ['g', 'ginv']
# Unknowns:   ['b_Tm_E_Tm', 'b_Tm_E_Tp', 'b_Tm_F_Tm', 'b_Tm_F_Tp', 'b_Tm_H_Tm', 'b_Tm_H_Tp', 'b_Tm_Tp_E', 'b_Tm_Tp_F', 'b_Tm_Tp_H', 'b_Tp_E_Tm', 'b_Tp_E_Tp', 'b_Tp_F_Tm', 'b_Tp_F_Tp', 'b_Tp_H_Tm', 'b_Tp_H_Tp']

var_names = ['g', 'ginv', 'b_Tm_E_Tm', 'b_Tm_E_Tp', 'b_Tm_F_Tm', 'b_Tm_F_Tp', 'b_Tm_H_Tm', 'b_Tm_H_Tp', 'b_Tm_Tp_E', 'b_Tm_Tp_F', 'b_Tm_Tp_H', 'b_Tp_E_Tm', 'b_Tp_E_Tp', 'b_Tp_F_Tm', 'b_Tp_F_Tp', 'b_Tp_H_Tm', 'b_Tp_H_Tp']

polys_raw = [
    '-b_Tm_E_Tp*b_Tp_F_Tm + b_Tm_E_Tp + b_Tm_F_Tp*b_Tp_E_Tm + b_Tp_F_Tm + b_Tp_H_Tp',
    '-b_Tm_E_Tm*b_Tp_F_Tm + b_Tm_E_Tm + b_Tm_F_Tm*b_Tp_E_Tm - b_Tp_E_Tm*b_Tp_F_Tp + b_Tp_E_Tp*b_Tp_F_Tm - b_Tp_E_Tp + b_Tp_H_Tm',
    'b_Tm_E_Tm*b_Tm_F_Tp - b_Tm_E_Tp*b_Tm_F_Tm + b_Tm_E_Tp*b_Tp_F_Tp + b_Tm_F_Tm - b_Tm_F_Tp*b_Tp_E_Tp + b_Tm_H_Tp - b_Tp_F_Tp',
    'b_Tm_E_Tp*b_Tp_F_Tm - b_Tm_E_Tp - b_Tm_F_Tp*b_Tp_E_Tm + b_Tm_H_Tm - b_Tp_F_Tm',
    '-b_Tm_E_Tp*b_Tp_H_Tm + b_Tm_H_Tp*b_Tp_E_Tm + b_Tp_E_Tp + b_Tp_H_Tm',
    '-b_Tm_E_Tm*b_Tp_H_Tm + b_Tm_H_Tm*b_Tp_E_Tm - b_Tp_E_Tm*b_Tp_H_Tp - b_Tp_E_Tm + b_Tp_E_Tp*b_Tp_H_Tm',
    'b_Tm_E_Tm*b_Tm_H_Tp - b_Tm_E_Tp*b_Tm_H_Tm + b_Tm_E_Tp*b_Tp_H_Tp + b_Tm_H_Tm - b_Tm_H_Tp*b_Tp_E_Tp - b_Tp_H_Tp',
    'b_Tm_E_Tm + b_Tm_E_Tp*b_Tp_H_Tm - b_Tm_H_Tp*b_Tp_E_Tm - b_Tp_H_Tm',
    '-b_Tm_E_Tp*b_Tp_E_Tm + b_Tp_E_Tm - b_Tp_E_Tp**2',
    '-b_Tm_E_Tm*b_Tp_E_Tm - b_Tp_E_Tm*b_Tp_E_Tp',
    '-b_Tm_E_Tp*b_Tp_F_Tm - b_Tp_E_Tp*b_Tp_F_Tp + b_Tp_F_Tm - b_Tp_H_Tp*ginv - b_Tp_H_Tp',
    '-b_Tm_E_Tm*b_Tp_F_Tm - b_Tp_E_Tm*b_Tp_F_Tp - b_Tp_H_Tm*ginv - b_Tp_H_Tm',
    '-b_Tm_E_Tp*b_Tp_H_Tm*ginv - b_Tp_E_Tp*b_Tp_H_Tp*ginv + b_Tp_E_Tp + b_Tp_H_Tm*ginv',
    '-b_Tm_E_Tm*b_Tp_H_Tm*ginv - b_Tp_E_Tm*b_Tp_H_Tp*ginv + b_Tp_E_Tm',
    '-b_Tm_Tp_E*b_Tp_E_Tm + b_Tp_E_Tp',
    '-b_Tm_Tp_F*b_Tp_E_Tm',
    '-b_Tm_Tp_H*b_Tp_E_Tm + b_Tp_E_Tm',
    '-b_Tm_E_Tm*b_Tm_Tp_E*ginv + b_Tm_E_Tp*ginv + b_Tm_Tp_H - ginv - 1',
    '-b_Tm_E_Tm*b_Tm_Tp_F',
    '-b_Tm_E_Tm*b_Tm_Tp_H + b_Tm_E_Tm - b_Tm_Tp_F*ginv - b_Tm_Tp_F',
    '-b_Tm_E_Tm*b_Tm_E_Tp + b_Tm_E_Tm - b_Tm_E_Tp*b_Tp_E_Tp - b_Tp_E_Tp',
    '-b_Tm_E_Tm**2 - b_Tm_E_Tp*b_Tp_E_Tm - b_Tp_E_Tm',
    '-b_Tm_E_Tp*b_Tm_F_Tm + b_Tm_F_Tm - b_Tm_F_Tp*b_Tp_E_Tp - b_Tm_H_Tp*ginv - b_Tm_H_Tp - b_Tp_F_Tp',
    '-b_Tm_E_Tm*b_Tm_F_Tm - b_Tm_F_Tp*b_Tp_E_Tm - b_Tm_H_Tm*ginv - b_Tm_H_Tm - b_Tp_F_Tm',
    '-b_Tm_E_Tp*b_Tm_H_Tm*ginv + b_Tm_E_Tp + b_Tm_H_Tm*ginv - b_Tm_H_Tp*b_Tp_E_Tp*ginv - b_Tp_H_Tp*ginv',
    '-b_Tm_E_Tm*b_Tm_H_Tm*ginv + b_Tm_E_Tm - b_Tm_H_Tp*b_Tp_E_Tm*ginv - b_Tp_H_Tm*ginv',
    'b_Tm_Tp_E*b_Tp_E_Tp*ginv - b_Tm_Tp_H - ginv',
    'b_Tm_Tp_F*b_Tp_E_Tp - b_Tp_E_Tm',
    'b_Tm_Tp_F*ginv + b_Tm_Tp_F + b_Tm_Tp_H*b_Tp_E_Tp',
    'b_Tm_E_Tp*b_Tm_Tp_E',
    '-b_Tm_E_Tm + b_Tm_E_Tp*b_Tm_Tp_F',
    'b_Tm_E_Tp*b_Tm_Tp_H - ginv + 1',
    'b_Tm_E_Tp*b_Tp_F_Tm - b_Tm_E_Tp - b_Tm_F_Tp*b_Tp_E_Tm - b_Tp_F_Tm - b_Tp_H_Tp',
    'b_Tm_E_Tm*b_Tp_F_Tm - b_Tm_E_Tm - b_Tm_F_Tm*b_Tp_E_Tm + b_Tp_E_Tm*b_Tp_F_Tp - b_Tp_E_Tp*b_Tp_F_Tm + b_Tp_E_Tp - b_Tp_H_Tm',
    '-b_Tm_E_Tm*b_Tm_F_Tp + b_Tm_E_Tp*b_Tm_F_Tm - b_Tm_E_Tp*b_Tp_F_Tp - b_Tm_F_Tm + b_Tm_F_Tp*b_Tp_E_Tp - b_Tm_H_Tp + b_Tp_F_Tp',
    '-b_Tm_E_Tp*b_Tp_F_Tm + b_Tm_E_Tp + b_Tm_F_Tp*b_Tp_E_Tm - b_Tm_H_Tm + b_Tp_F_Tm',
    '-b_Tm_F_Tp*b_Tp_H_Tm + b_Tm_H_Tp*b_Tp_F_Tm - b_Tm_H_Tp - b_Tp_F_Tp',
    '-b_Tm_F_Tm*b_Tp_H_Tm + b_Tm_H_Tm*b_Tp_F_Tm - b_Tm_H_Tm - b_Tp_F_Tm*b_Tp_H_Tp + b_Tp_F_Tp*b_Tp_H_Tm + b_Tp_H_Tp',
    'b_Tm_F_Tm*b_Tm_H_Tp - b_Tm_F_Tp*b_Tm_H_Tm + b_Tm_F_Tp*b_Tp_H_Tp + b_Tm_F_Tp - b_Tm_H_Tp*b_Tp_F_Tp',
    '-b_Tm_F_Tm + b_Tm_F_Tp*b_Tp_H_Tm - b_Tm_H_Tp*b_Tp_F_Tm + b_Tm_H_Tp',
    '-b_Tm_E_Tp - b_Tm_F_Tp*b_Tp_E_Tm - b_Tp_E_Tp*b_Tp_F_Tp - b_Tp_H_Tp*ginv + b_Tp_H_Tp',
    '-b_Tm_E_Tm - b_Tm_F_Tm*b_Tp_E_Tm - b_Tp_E_Tp*b_Tp_F_Tm + b_Tp_E_Tp - b_Tp_H_Tm*ginv + b_Tp_H_Tm',
    '-b_Tm_F_Tp*b_Tp_F_Tm - b_Tm_F_Tp - b_Tp_F_Tp**2',
    '-b_Tm_F_Tm*b_Tp_F_Tm - b_Tm_F_Tm - b_Tp_F_Tm*b_Tp_F_Tp + b_Tp_F_Tp',
    '-b_Tm_F_Tp*b_Tp_H_Tm*ginv - b_Tm_H_Tp*ginv - b_Tp_F_Tp*b_Tp_H_Tp*ginv + b_Tp_F_Tp',
    '-b_Tm_F_Tm*b_Tp_H_Tm*ginv - b_Tm_H_Tm*ginv - b_Tp_F_Tm*b_Tp_H_Tp*ginv + b_Tp_F_Tm + b_Tp_H_Tp*ginv',
    '-b_Tm_Tp_E*b_Tp_F_Tm + b_Tp_F_Tp',
    '-b_Tm_Tp_F*b_Tp_F_Tm',
    '-b_Tm_Tp_H*b_Tp_F_Tm + b_Tp_F_Tm + ginv + 1',
    '-b_Tm_F_Tm*b_Tm_Tp_E + b_Tm_F_Tp',
    '-b_Tm_F_Tm*b_Tm_Tp_F*ginv + b_Tm_Tp_H + ginv - 1',
    '-b_Tm_F_Tm*b_Tm_Tp_H + b_Tm_F_Tm - b_Tm_Tp_E*ginv + b_Tm_Tp_E',
    '-b_Tm_E_Tm*b_Tm_F_Tp - b_Tm_E_Tp*b_Tp_F_Tp - b_Tm_H_Tp*ginv + b_Tm_H_Tp',
    '-b_Tm_E_Tm*b_Tm_F_Tm - b_Tm_E_Tp*b_Tp_F_Tm + b_Tm_E_Tp - b_Tm_H_Tm*ginv + b_Tm_H_Tm',
    '-b_Tm_F_Tm*b_Tm_F_Tp - b_Tm_F_Tp*b_Tp_F_Tp',
    '-b_Tm_F_Tm**2 - b_Tm_F_Tp*b_Tp_F_Tm + b_Tm_F_Tp',
    '-b_Tm_F_Tp*b_Tm_H_Tm*ginv + b_Tm_F_Tp - b_Tm_H_Tp*b_Tp_F_Tp*ginv',
    '-b_Tm_F_Tm*b_Tm_H_Tm*ginv + b_Tm_F_Tm - b_Tm_H_Tp*b_Tp_F_Tm*ginv + b_Tm_H_Tp*ginv',
    'b_Tm_Tp_E*b_Tp_F_Tp',
    'b_Tm_Tp_F*b_Tp_F_Tp*ginv - b_Tm_Tp_H - b_Tp_F_Tm*ginv + ginv',
    'b_Tm_Tp_E*ginv - b_Tm_Tp_E + b_Tm_Tp_H*b_Tp_F_Tp',
    'b_Tm_F_Tp*b_Tm_Tp_E',
    '-b_Tm_F_Tm + b_Tm_F_Tp*b_Tm_Tp_F',
    'b_Tm_F_Tp*b_Tm_Tp_H',
    'b_Tm_E_Tp*b_Tp_H_Tm - b_Tm_H_Tp*b_Tp_E_Tm - b_Tp_E_Tp - b_Tp_H_Tm',
    'b_Tm_E_Tm*b_Tp_H_Tm - b_Tm_H_Tm*b_Tp_E_Tm + b_Tp_E_Tm*b_Tp_H_Tp + b_Tp_E_Tm - b_Tp_E_Tp*b_Tp_H_Tm',
    '-b_Tm_E_Tm*b_Tm_H_Tp + b_Tm_E_Tp*b_Tm_H_Tm - b_Tm_E_Tp*b_Tp_H_Tp - b_Tm_H_Tm + b_Tm_H_Tp*b_Tp_E_Tp + b_Tp_H_Tp',
    '-b_Tm_E_Tm - b_Tm_E_Tp*b_Tp_H_Tm + b_Tm_H_Tp*b_Tp_E_Tm + b_Tp_H_Tm',
    'b_Tm_F_Tp*b_Tp_H_Tm - b_Tm_H_Tp*b_Tp_F_Tm + b_Tm_H_Tp + b_Tp_F_Tp',
    'b_Tm_F_Tm*b_Tp_H_Tm - b_Tm_H_Tm*b_Tp_F_Tm + b_Tm_H_Tm + b_Tp_F_Tm*b_Tp_H_Tp - b_Tp_F_Tp*b_Tp_H_Tm - b_Tp_H_Tp',
    '-b_Tm_F_Tm*b_Tm_H_Tp + b_Tm_F_Tp*b_Tm_H_Tm - b_Tm_F_Tp*b_Tp_H_Tp - b_Tm_F_Tp + b_Tm_H_Tp*b_Tp_F_Tp',
    'b_Tm_F_Tm - b_Tm_F_Tp*b_Tp_H_Tm + b_Tm_H_Tp*b_Tp_F_Tm - b_Tm_H_Tp',
    '-b_Tm_H_Tp*b_Tp_E_Tm*ginv - b_Tp_E_Tp*b_Tp_H_Tp*ginv - b_Tp_E_Tp*ginv + b_Tp_E_Tp',
    '-b_Tm_H_Tm*b_Tp_E_Tm*ginv + b_Tp_E_Tm*ginv + b_Tp_E_Tm - b_Tp_E_Tp*b_Tp_H_Tm*ginv',
    '-b_Tm_H_Tp*b_Tp_F_Tm*ginv - b_Tp_F_Tp*b_Tp_H_Tp*ginv + b_Tp_F_Tp*ginv + b_Tp_F_Tp',
    '-b_Tm_H_Tm*b_Tp_F_Tm*ginv + b_Tp_F_Tm - b_Tp_F_Tp*b_Tp_H_Tm*ginv',
    '-b_Tm_H_Tp*b_Tp_H_Tm*ginv - b_Tp_H_Tp**2*ginv + b_Tp_H_Tp',
    '-b_Tm_H_Tm*b_Tp_H_Tm*ginv - b_Tp_H_Tm*b_Tp_H_Tp*ginv - b_Tp_H_Tm*ginv + b_Tp_H_Tm',
    '-b_Tm_Tp_E*b_Tp_H_Tm*ginv + b_Tp_H_Tp*ginv - 1',
    '-b_Tm_Tp_F*b_Tp_H_Tm',
    '-b_Tm_Tp_H*b_Tp_H_Tm + b_Tp_H_Tm',
    '-b_Tm_H_Tm*b_Tm_Tp_E*ginv + b_Tm_H_Tp*ginv - b_Tm_Tp_E*ginv + b_Tm_Tp_E',
    '-b_Tm_H_Tm*b_Tm_Tp_F*ginv + b_Tm_Tp_F*ginv + b_Tm_Tp_F',
    '-b_Tm_H_Tm*b_Tm_Tp_H*ginv + b_Tm_H_Tm*ginv + b_Tm_Tp_H - 1',
    '-b_Tm_E_Tm*b_Tm_H_Tp*ginv - b_Tm_E_Tp*b_Tp_H_Tp*ginv + b_Tm_E_Tp',
    '-b_Tm_E_Tm*b_Tm_H_Tm*ginv - b_Tm_E_Tm*ginv + b_Tm_E_Tm - b_Tm_E_Tp*b_Tp_H_Tm*ginv',
    '-b_Tm_F_Tm*b_Tm_H_Tp*ginv - b_Tm_F_Tp*b_Tp_H_Tp*ginv - b_Tm_F_Tp*ginv + b_Tm_F_Tp',
    '-b_Tm_F_Tm*b_Tm_H_Tm*ginv + b_Tm_F_Tm*ginv + b_Tm_F_Tm - b_Tm_F_Tp*b_Tp_H_Tm*ginv',
    '-b_Tm_H_Tm*b_Tm_H_Tp*ginv - b_Tm_H_Tp*b_Tp_H_Tp*ginv + b_Tm_H_Tp*ginv + b_Tm_H_Tp',
    '-b_Tm_H_Tm**2*ginv + b_Tm_H_Tm - b_Tm_H_Tp*b_Tp_H_Tm*ginv',
    'b_Tm_Tp_E*b_Tp_H_Tp*ginv + b_Tm_Tp_E*ginv - b_Tm_Tp_E',
    'b_Tm_Tp_F*b_Tp_H_Tp*ginv - b_Tm_Tp_F*ginv - b_Tm_Tp_F - b_Tp_H_Tm*ginv',
    'b_Tm_Tp_H*b_Tp_H_Tp*ginv - b_Tm_Tp_H',
    'b_Tm_H_Tp*b_Tm_Tp_E',
    '-b_Tm_H_Tm*ginv + b_Tm_H_Tp*b_Tm_Tp_F*ginv + 1',
    'b_Tm_H_Tp*b_Tm_Tp_H',
    'b_Tm_E_Tp*b_Tp_E_Tm - b_Tp_E_Tm + b_Tp_E_Tp**2',
    'b_Tm_E_Tm*b_Tp_E_Tm + b_Tp_E_Tm*b_Tp_E_Tp',
    'b_Tm_E_Tp*b_Tp_F_Tm + b_Tp_E_Tp*b_Tp_F_Tp - b_Tp_F_Tm + b_Tp_H_Tp*ginv + b_Tp_H_Tp',
    'b_Tm_E_Tm*b_Tp_F_Tm + b_Tp_E_Tm*b_Tp_F_Tp + b_Tp_H_Tm*ginv + b_Tp_H_Tm',
    'b_Tm_E_Tp*b_Tp_H_Tm*ginv + b_Tp_E_Tp*b_Tp_H_Tp*ginv - b_Tp_E_Tp - b_Tp_H_Tm*ginv',
    'b_Tm_E_Tm*b_Tp_H_Tm*ginv + b_Tp_E_Tm*b_Tp_H_Tp*ginv - b_Tp_E_Tm',
    'b_Tm_Tp_E*b_Tp_E_Tm - b_Tp_E_Tp',
    'b_Tm_Tp_F*b_Tp_E_Tm',
    'b_Tm_Tp_H*b_Tp_E_Tm - b_Tp_E_Tm',
    'b_Tm_E_Tm*b_Tm_Tp_E*ginv - b_Tm_E_Tp*ginv - b_Tm_Tp_H + ginv + 1',
    'b_Tm_E_Tm*b_Tm_Tp_F',
    'b_Tm_E_Tm*b_Tm_Tp_H - b_Tm_E_Tm + b_Tm_Tp_F*ginv + b_Tm_Tp_F',
    'b_Tm_E_Tp + b_Tm_F_Tp*b_Tp_E_Tm + b_Tp_E_Tp*b_Tp_F_Tp + b_Tp_H_Tp*ginv - b_Tp_H_Tp',
    'b_Tm_E_Tm + b_Tm_F_Tm*b_Tp_E_Tm + b_Tp_E_Tp*b_Tp_F_Tm - b_Tp_E_Tp + b_Tp_H_Tm*ginv - b_Tp_H_Tm',
    'b_Tm_F_Tp*b_Tp_F_Tm + b_Tm_F_Tp + b_Tp_F_Tp**2',
    'b_Tm_F_Tm*b_Tp_F_Tm + b_Tm_F_Tm + b_Tp_F_Tm*b_Tp_F_Tp - b_Tp_F_Tp',
    'b_Tm_F_Tp*b_Tp_H_Tm*ginv + b_Tm_H_Tp*ginv + b_Tp_F_Tp*b_Tp_H_Tp*ginv - b_Tp_F_Tp',
    'b_Tm_F_Tm*b_Tp_H_Tm*ginv + b_Tm_H_Tm*ginv + b_Tp_F_Tm*b_Tp_H_Tp*ginv - b_Tp_F_Tm - b_Tp_H_Tp*ginv',
    'b_Tm_Tp_E*b_Tp_F_Tm - b_Tp_F_Tp',
    'b_Tm_Tp_F*b_Tp_F_Tm',
    'b_Tm_Tp_H*b_Tp_F_Tm - b_Tp_F_Tm - ginv - 1',
    'b_Tm_F_Tm*b_Tm_Tp_E - b_Tm_F_Tp',
    'b_Tm_F_Tm*b_Tm_Tp_F*ginv - b_Tm_Tp_H - ginv + 1',
    'b_Tm_F_Tm*b_Tm_Tp_H - b_Tm_F_Tm + b_Tm_Tp_E*ginv - b_Tm_Tp_E',
    'b_Tm_H_Tp*b_Tp_E_Tm*ginv + b_Tp_E_Tp*b_Tp_H_Tp*ginv + b_Tp_E_Tp*ginv - b_Tp_E_Tp',
    'b_Tm_H_Tm*b_Tp_E_Tm*ginv - b_Tp_E_Tm*ginv - b_Tp_E_Tm + b_Tp_E_Tp*b_Tp_H_Tm*ginv',
    'b_Tm_H_Tp*b_Tp_F_Tm*ginv + b_Tp_F_Tp*b_Tp_H_Tp*ginv - b_Tp_F_Tp*ginv - b_Tp_F_Tp',
    'b_Tm_H_Tm*b_Tp_F_Tm*ginv - b_Tp_F_Tm + b_Tp_F_Tp*b_Tp_H_Tm*ginv',
    'b_Tm_H_Tp*b_Tp_H_Tm*ginv + b_Tp_H_Tp**2*ginv - b_Tp_H_Tp',
    'b_Tm_H_Tm*b_Tp_H_Tm*ginv + b_Tp_H_Tm*b_Tp_H_Tp*ginv + b_Tp_H_Tm*ginv - b_Tp_H_Tm',
    'b_Tm_Tp_E*b_Tp_H_Tm*ginv - b_Tp_H_Tp*ginv + 1',
    'b_Tm_Tp_F*b_Tp_H_Tm',
    'b_Tm_Tp_H*b_Tp_H_Tm - b_Tp_H_Tm',
    'b_Tm_H_Tm*b_Tm_Tp_E*ginv - b_Tm_H_Tp*ginv + b_Tm_Tp_E*ginv - b_Tm_Tp_E',
    'b_Tm_H_Tm*b_Tm_Tp_F*ginv - b_Tm_Tp_F*ginv - b_Tm_Tp_F',
    'b_Tm_H_Tm*b_Tm_Tp_H*ginv - b_Tm_H_Tm*ginv - b_Tm_Tp_H + 1',
    '-b_Tm_Tp_E*b_Tp_E_Tm + b_Tp_E_Tp',
    '-b_Tm_Tp_F*b_Tp_E_Tm',
    '-b_Tm_Tp_H*b_Tp_E_Tm + b_Tp_E_Tm',
    '-b_Tm_Tp_E*b_Tp_F_Tm + b_Tp_F_Tp',
    '-b_Tm_Tp_F*b_Tp_F_Tm',
    '-b_Tm_Tp_H*b_Tp_F_Tm + b_Tp_F_Tm + ginv + 1',
    '-b_Tm_Tp_E*b_Tp_H_Tm*ginv + b_Tp_H_Tp*ginv - 1',
    '-b_Tm_Tp_F*b_Tp_H_Tm',
    '-b_Tm_Tp_H*b_Tp_H_Tm + b_Tp_H_Tm',
    '-b_Tm_E_Tp - b_Tm_Tp_E*b_Tp_E_Tp - b_Tm_Tp_F*b_Tp_F_Tp - b_Tm_Tp_H*b_Tp_H_Tp + b_Tp_H_Tp + 1',
    '-b_Tm_E_Tm - b_Tm_Tp_E*b_Tp_E_Tm - b_Tm_Tp_F*b_Tp_F_Tm - b_Tm_Tp_H*b_Tp_H_Tm + b_Tp_H_Tm',
    'b_Tm_E_Tm*b_Tm_Tp_E*ginv - b_Tm_E_Tp*ginv - b_Tm_Tp_E*b_Tp_E_Tp*ginv - ginv + 1',
    'b_Tm_E_Tm*b_Tm_Tp_F - b_Tm_Tp_F*b_Tp_E_Tp + b_Tp_E_Tm',
    'b_Tm_E_Tm*b_Tm_Tp_H - b_Tm_E_Tm - b_Tm_Tp_H*b_Tp_E_Tp',
    'b_Tm_F_Tm*b_Tm_Tp_E - b_Tm_F_Tp - b_Tm_Tp_E*b_Tp_F_Tp',
    'b_Tm_F_Tm*b_Tm_Tp_F*ginv - b_Tm_Tp_F*b_Tp_F_Tp*ginv + b_Tp_F_Tm*ginv + ginv + 1',
    'b_Tm_F_Tm*b_Tm_Tp_H - b_Tm_F_Tm - b_Tm_Tp_H*b_Tp_F_Tp',
    'b_Tm_H_Tm*b_Tm_Tp_E - b_Tm_H_Tp - b_Tm_Tp_E*b_Tp_H_Tp',
    'b_Tm_H_Tm*b_Tm_Tp_F - b_Tm_Tp_F*b_Tp_H_Tp + b_Tp_H_Tm',
    'b_Tm_H_Tm*b_Tm_Tp_H*ginv - b_Tm_H_Tm*ginv - b_Tm_Tp_H*b_Tp_H_Tp*ginv + 1',
    '-b_Tm_E_Tp - b_Tm_Tp_E*b_Tp_E_Tp - b_Tm_Tp_F*b_Tp_F_Tp - b_Tm_Tp_H*b_Tp_H_Tp + b_Tp_H_Tp + 1',
    '-b_Tm_E_Tm - b_Tm_Tp_E*b_Tp_E_Tm - b_Tm_Tp_F*b_Tp_F_Tm - b_Tm_Tp_H*b_Tp_H_Tm + b_Tp_H_Tm',
    'b_Tm_E_Tp*b_Tm_Tp_E + b_Tm_F_Tp*b_Tm_Tp_F + b_Tm_H_Tp*b_Tm_Tp_H + b_Tp_F_Tp',
    'b_Tm_E_Tm*b_Tm_Tp_E + b_Tm_F_Tm*b_Tm_Tp_F + b_Tm_H_Tm*b_Tm_Tp_H + b_Tp_F_Tm - 1',
    'b_Tm_E_Tm*b_Tm_E_Tp - b_Tm_E_Tm + b_Tm_E_Tp*b_Tp_E_Tp + b_Tp_E_Tp',
    'b_Tm_E_Tm**2 + b_Tm_E_Tp*b_Tp_E_Tm + b_Tp_E_Tm',
    'b_Tm_E_Tp*b_Tm_F_Tm - b_Tm_F_Tm + b_Tm_F_Tp*b_Tp_E_Tp + b_Tm_H_Tp*ginv + b_Tm_H_Tp + b_Tp_F_Tp',
    'b_Tm_E_Tm*b_Tm_F_Tm + b_Tm_F_Tp*b_Tp_E_Tm + b_Tm_H_Tm*ginv + b_Tm_H_Tm + b_Tp_F_Tm',
    'b_Tm_E_Tp*b_Tm_H_Tm*ginv - b_Tm_E_Tp - b_Tm_H_Tm*ginv + b_Tm_H_Tp*b_Tp_E_Tp*ginv + b_Tp_H_Tp*ginv',
    'b_Tm_E_Tm*b_Tm_H_Tm*ginv - b_Tm_E_Tm + b_Tm_H_Tp*b_Tp_E_Tm*ginv + b_Tp_H_Tm*ginv',
    '-b_Tm_Tp_E*b_Tp_E_Tp*ginv + b_Tm_Tp_H + ginv',
    '-b_Tm_Tp_F*b_Tp_E_Tp + b_Tp_E_Tm',
    '-b_Tm_Tp_F*ginv - b_Tm_Tp_F - b_Tm_Tp_H*b_Tp_E_Tp',
    '-b_Tm_E_Tp*b_Tm_Tp_E',
    'b_Tm_E_Tm - b_Tm_E_Tp*b_Tm_Tp_F',
    '-b_Tm_E_Tp*b_Tm_Tp_H + ginv - 1',
    'b_Tm_E_Tm*b_Tm_F_Tp + b_Tm_E_Tp*b_Tp_F_Tp + b_Tm_H_Tp*ginv - b_Tm_H_Tp',
    'b_Tm_E_Tm*b_Tm_F_Tm + b_Tm_E_Tp*b_Tp_F_Tm - b_Tm_E_Tp + b_Tm_H_Tm*ginv - b_Tm_H_Tm',
    'b_Tm_F_Tm*b_Tm_F_Tp + b_Tm_F_Tp*b_Tp_F_Tp',
    'b_Tm_F_Tm**2 + b_Tm_F_Tp*b_Tp_F_Tm - b_Tm_F_Tp',
    'b_Tm_F_Tp*b_Tm_H_Tm*ginv - b_Tm_F_Tp + b_Tm_H_Tp*b_Tp_F_Tp*ginv',
    'b_Tm_F_Tm*b_Tm_H_Tm*ginv - b_Tm_F_Tm + b_Tm_H_Tp*b_Tp_F_Tm*ginv - b_Tm_H_Tp*ginv',
    '-b_Tm_Tp_E*b_Tp_F_Tp',
    '-b_Tm_Tp_F*b_Tp_F_Tp*ginv + b_Tm_Tp_H + b_Tp_F_Tm*ginv - ginv',
    '-b_Tm_Tp_E*ginv + b_Tm_Tp_E - b_Tm_Tp_H*b_Tp_F_Tp',
    '-b_Tm_F_Tp*b_Tm_Tp_E',
    'b_Tm_F_Tm - b_Tm_F_Tp*b_Tm_Tp_F',
    '-b_Tm_F_Tp*b_Tm_Tp_H',
    'b_Tm_E_Tm*b_Tm_H_Tp*ginv + b_Tm_E_Tp*b_Tp_H_Tp*ginv - b_Tm_E_Tp',
    'b_Tm_E_Tm*b_Tm_H_Tm*ginv + b_Tm_E_Tm*ginv - b_Tm_E_Tm + b_Tm_E_Tp*b_Tp_H_Tm*ginv',
    'b_Tm_F_Tm*b_Tm_H_Tp*ginv + b_Tm_F_Tp*b_Tp_H_Tp*ginv + b_Tm_F_Tp*ginv - b_Tm_F_Tp',
    'b_Tm_F_Tm*b_Tm_H_Tm*ginv - b_Tm_F_Tm*ginv - b_Tm_F_Tm + b_Tm_F_Tp*b_Tp_H_Tm*ginv',
    'b_Tm_H_Tm*b_Tm_H_Tp*ginv + b_Tm_H_Tp*b_Tp_H_Tp*ginv - b_Tm_H_Tp*ginv - b_Tm_H_Tp',
    'b_Tm_H_Tm**2*ginv - b_Tm_H_Tm + b_Tm_H_Tp*b_Tp_H_Tm*ginv',
    '-b_Tm_Tp_E*b_Tp_H_Tp*ginv - b_Tm_Tp_E*ginv + b_Tm_Tp_E',
    '-b_Tm_Tp_F*b_Tp_H_Tp*ginv + b_Tm_Tp_F*ginv + b_Tm_Tp_F + b_Tp_H_Tm*ginv',
    '-b_Tm_Tp_H*b_Tp_H_Tp*ginv + b_Tm_Tp_H',
    '-b_Tm_H_Tp*b_Tm_Tp_E',
    'b_Tm_H_Tm*ginv - b_Tm_H_Tp*b_Tm_Tp_F*ginv - 1',
    '-b_Tm_H_Tp*b_Tm_Tp_H',
    'b_Tm_E_Tp*b_Tm_Tp_E',
    '-b_Tm_E_Tm + b_Tm_E_Tp*b_Tm_Tp_F',
    'b_Tm_E_Tp*b_Tm_Tp_H - ginv + 1',
    'b_Tm_F_Tp*b_Tm_Tp_E',
    '-b_Tm_F_Tm + b_Tm_F_Tp*b_Tm_Tp_F',
    'b_Tm_F_Tp*b_Tm_Tp_H',
    'b_Tm_H_Tp*b_Tm_Tp_E',
    '-b_Tm_H_Tm*ginv + b_Tm_H_Tp*b_Tm_Tp_F*ginv + 1',
    'b_Tm_H_Tp*b_Tm_Tp_H',
    'b_Tm_E_Tp*b_Tm_Tp_E + b_Tm_F_Tp*b_Tm_Tp_F + b_Tm_H_Tp*b_Tm_Tp_H + b_Tp_F_Tp',
    'b_Tm_E_Tm*b_Tm_Tp_E + b_Tm_F_Tm*b_Tm_Tp_F + b_Tm_H_Tm*b_Tm_Tp_H + b_Tp_F_Tm - 1',
    'g*ginv - 1',
]
