# Auto-generated for SageMath — Structure 1
# All variables in b_X_Y_Z form (no tau symbols).
# Parameters: ['u', 'v']
# Unknowns:   ['b_Tm_E_Tm', 'b_Tm_E_Tp', 'b_Tm_F_Tm', 'b_Tm_F_Tp', 'b_Tm_H_Tm', 'b_Tm_H_Tp', 'b_Tm_Tp_E', 'b_Tm_Tp_F', 'b_Tm_Tp_H', 'b_Tp_E_Tm', 'b_Tp_E_Tp', 'b_Tp_F_Tm', 'b_Tp_F_Tp', 'b_Tp_H_Tm', 'b_Tp_H_Tp']

var_names = ['u', 'v', 'b_Tm_E_Tm', 'b_Tm_E_Tp', 'b_Tm_F_Tm', 'b_Tm_F_Tp', 'b_Tm_H_Tm', 'b_Tm_H_Tp', 'b_Tm_Tp_E', 'b_Tm_Tp_F', 'b_Tm_Tp_H', 'b_Tp_E_Tm', 'b_Tp_E_Tp', 'b_Tp_F_Tm', 'b_Tp_F_Tp', 'b_Tp_H_Tm', 'b_Tp_H_Tp']

polys_raw = [
    '-b_Tm_E_Tp*b_Tp_F_Tm + b_Tm_E_Tp + b_Tm_F_Tp*b_Tp_E_Tm + b_Tp_F_Tm + b_Tp_H_Tp',
    '-b_Tm_E_Tm*b_Tp_F_Tm + b_Tm_E_Tm + b_Tm_F_Tm*b_Tp_E_Tm - b_Tp_E_Tm*b_Tp_F_Tp + b_Tp_E_Tp*b_Tp_F_Tm - b_Tp_E_Tp + b_Tp_H_Tm',
    'b_Tm_E_Tm*b_Tm_F_Tp - b_Tm_E_Tp*b_Tm_F_Tm + b_Tm_E_Tp*b_Tp_F_Tp + b_Tm_F_Tm - b_Tm_F_Tp*b_Tp_E_Tp + b_Tm_H_Tp - b_Tp_F_Tp',
    'b_Tm_E_Tp*b_Tp_F_Tm - b_Tm_E_Tp - b_Tm_F_Tp*b_Tp_E_Tm + b_Tm_H_Tm - b_Tp_F_Tm',
    '-b_Tm_E_Tp*b_Tp_H_Tm + b_Tm_H_Tp*b_Tp_E_Tm + b_Tp_E_Tp + b_Tp_H_Tm',
    '-b_Tm_E_Tm*b_Tp_H_Tm + b_Tm_H_Tm*b_Tp_E_Tm - b_Tp_E_Tm*b_Tp_H_Tp - b_Tp_E_Tm + b_Tp_E_Tp*b_Tp_H_Tm',
    'b_Tm_E_Tm*b_Tm_H_Tp - b_Tm_E_Tp*b_Tm_H_Tm + b_Tm_E_Tp*b_Tp_H_Tp + b_Tm_H_Tm - b_Tm_H_Tp*b_Tp_E_Tp - b_Tp_H_Tp',
    'b_Tm_E_Tm + b_Tm_E_Tp*b_Tp_H_Tm - b_Tm_H_Tp*b_Tp_E_Tm - b_Tp_H_Tm',
    '-b_Tm_E_Tp*b_Tp_E_Tm + b_Tp_E_Tm - b_Tp_E_Tp**2 + b_Tp_H_Tp',
    '-b_Tm_E_Tm*b_Tp_E_Tm - b_Tp_E_Tm*b_Tp_E_Tp + b_Tp_H_Tm',
    '-b_Tm_E_Tp*b_Tp_F_Tm - b_Tp_E_Tp*b_Tp_F_Tp + b_Tp_E_Tp*u + b_Tp_F_Tm - b_Tp_F_Tp*u + b_Tp_F_Tp*v + b_Tp_H_Tp*u**2 + b_Tp_H_Tp*u*v + b_Tp_H_Tp*v**2 + b_Tp_H_Tp',
    '-b_Tm_E_Tm*b_Tp_F_Tm - b_Tp_E_Tm*b_Tp_F_Tp + b_Tp_E_Tm*u - b_Tp_F_Tm*u + b_Tp_F_Tm*v + b_Tp_H_Tm*u**2 + b_Tp_H_Tm*u*v + b_Tp_H_Tm*v**2 + b_Tp_H_Tm',
    '-b_Tm_E_Tp*b_Tp_H_Tm - b_Tp_E_Tp*b_Tp_H_Tp + b_Tp_E_Tp - b_Tp_F_Tp + b_Tp_H_Tm + b_Tp_H_Tp*u - b_Tp_H_Tp*v',
    '-b_Tm_E_Tm*b_Tp_H_Tm - b_Tp_E_Tm*b_Tp_H_Tp + b_Tp_E_Tm - b_Tp_F_Tm + b_Tp_H_Tm*u - b_Tp_H_Tm*v',
    '-b_Tm_Tp_E*b_Tp_E_Tm + b_Tp_E_Tp',
    '-b_Tm_Tp_F*b_Tp_E_Tm',
    '-b_Tm_Tp_H*b_Tp_E_Tm + b_Tp_E_Tm - 1',
    '-b_Tm_E_Tm*b_Tm_Tp_E + b_Tm_E_Tp + b_Tm_Tp_F*u + b_Tm_Tp_H + 1',
    '-b_Tm_E_Tm*b_Tm_Tp_F - b_Tm_Tp_F*u + b_Tm_Tp_F*v - b_Tm_Tp_H + 1',
    '-b_Tm_E_Tm*b_Tm_Tp_H + b_Tm_E_Tm + b_Tm_Tp_E + b_Tm_Tp_F*u**2 + b_Tm_Tp_F*u*v + b_Tm_Tp_F*v**2 + b_Tm_Tp_F + b_Tm_Tp_H*u - b_Tm_Tp_H*v - u + v',
    '-b_Tm_E_Tm*b_Tm_E_Tp + b_Tm_E_Tm - b_Tm_E_Tp*b_Tp_E_Tp + b_Tm_H_Tp - b_Tp_E_Tp',
    '-b_Tm_E_Tm**2 - b_Tm_E_Tp*b_Tp_E_Tm + b_Tm_H_Tm - b_Tp_E_Tm',
    '-b_Tm_E_Tp*b_Tm_F_Tm + b_Tm_E_Tp*u + b_Tm_F_Tm - b_Tm_F_Tp*b_Tp_E_Tp - b_Tm_F_Tp*u + b_Tm_F_Tp*v + b_Tm_H_Tp*u**2 + b_Tm_H_Tp*u*v + b_Tm_H_Tp*v**2 + b_Tm_H_Tp - b_Tp_F_Tp',
    '-b_Tm_E_Tm*b_Tm_F_Tm + b_Tm_E_Tm*u - b_Tm_F_Tm*u + b_Tm_F_Tm*v - b_Tm_F_Tp*b_Tp_E_Tm + b_Tm_H_Tm*u**2 + b_Tm_H_Tm*u*v + b_Tm_H_Tm*v**2 + b_Tm_H_Tm - b_Tp_F_Tm',
    '-b_Tm_E_Tp*b_Tm_H_Tm + b_Tm_E_Tp - b_Tm_F_Tp + b_Tm_H_Tm - b_Tm_H_Tp*b_Tp_E_Tp + b_Tm_H_Tp*u - b_Tm_H_Tp*v - b_Tp_H_Tp',
    '-b_Tm_E_Tm*b_Tm_H_Tm + b_Tm_E_Tm - b_Tm_F_Tm + b_Tm_H_Tm*u - b_Tm_H_Tm*v - b_Tm_H_Tp*b_Tp_E_Tm - b_Tp_H_Tm',
    'b_Tm_Tp_E*b_Tp_E_Tp - b_Tm_Tp_F*u - b_Tm_Tp_H - 1',
    'b_Tm_Tp_F*b_Tp_E_Tp + b_Tm_Tp_F*u - b_Tm_Tp_F*v + b_Tm_Tp_H - b_Tp_E_Tm',
    '-b_Tm_Tp_E - b_Tm_Tp_F*u**2 - b_Tm_Tp_F*u*v - b_Tm_Tp_F*v**2 - b_Tm_Tp_F + b_Tm_Tp_H*b_Tp_E_Tp - b_Tm_Tp_H*u + b_Tm_Tp_H*v',
    'b_Tm_E_Tp*b_Tm_Tp_E + u',
    '-b_Tm_E_Tm + b_Tm_E_Tp*b_Tm_Tp_F - u + v',
    'b_Tm_E_Tp*b_Tm_Tp_H + u**2 + u*v + v**2',
    'b_Tm_E_Tp*b_Tp_F_Tm - b_Tm_E_Tp - b_Tm_F_Tp*b_Tp_E_Tm - b_Tp_F_Tm - b_Tp_H_Tp',
    'b_Tm_E_Tm*b_Tp_F_Tm - b_Tm_E_Tm - b_Tm_F_Tm*b_Tp_E_Tm + b_Tp_E_Tm*b_Tp_F_Tp - b_Tp_E_Tp*b_Tp_F_Tm + b_Tp_E_Tp - b_Tp_H_Tm',
    '-b_Tm_E_Tm*b_Tm_F_Tp + b_Tm_E_Tp*b_Tm_F_Tm - b_Tm_E_Tp*b_Tp_F_Tp - b_Tm_F_Tm + b_Tm_F_Tp*b_Tp_E_Tp - b_Tm_H_Tp + b_Tp_F_Tp',
    '-b_Tm_E_Tp*b_Tp_F_Tm + b_Tm_E_Tp + b_Tm_F_Tp*b_Tp_E_Tm - b_Tm_H_Tm + b_Tp_F_Tm',
    '-b_Tm_F_Tp*b_Tp_H_Tm + b_Tm_H_Tp*b_Tp_F_Tm - b_Tm_H_Tp - b_Tp_F_Tp',
    '-b_Tm_F_Tm*b_Tp_H_Tm + b_Tm_H_Tm*b_Tp_F_Tm - b_Tm_H_Tm - b_Tp_F_Tm*b_Tp_H_Tp + b_Tp_F_Tp*b_Tp_H_Tm + b_Tp_H_Tp',
    'b_Tm_F_Tm*b_Tm_H_Tp - b_Tm_F_Tp*b_Tm_H_Tm + b_Tm_F_Tp*b_Tp_H_Tp + b_Tm_F_Tp - b_Tm_H_Tp*b_Tp_F_Tp',
    '-b_Tm_F_Tm + b_Tm_F_Tp*b_Tp_H_Tm - b_Tm_H_Tp*b_Tp_F_Tm + b_Tm_H_Tp',
    '-b_Tm_E_Tp - b_Tm_F_Tp*b_Tp_E_Tm - b_Tp_E_Tp*b_Tp_F_Tp + b_Tp_E_Tp*u - b_Tp_F_Tp*u + b_Tp_F_Tp*v + b_Tp_H_Tp*u**2 + b_Tp_H_Tp*u*v + b_Tp_H_Tp*v**2',
    '-b_Tm_E_Tm - b_Tm_F_Tm*b_Tp_E_Tm + b_Tp_E_Tm*u - b_Tp_E_Tp*b_Tp_F_Tm + b_Tp_E_Tp - b_Tp_F_Tm*u + b_Tp_F_Tm*v + b_Tp_H_Tm*u**2 + b_Tp_H_Tm*u*v + b_Tp_H_Tm*v**2',
    '-b_Tm_F_Tp*b_Tp_F_Tm - b_Tm_F_Tp - b_Tp_E_Tp*u**2*v - b_Tp_E_Tp*u*v**2 + b_Tp_E_Tp*u - b_Tp_E_Tp*v**3 - b_Tp_F_Tp**2 + b_Tp_F_Tp*v + b_Tp_H_Tp*u*v - b_Tp_H_Tp*v**2',
    '-b_Tm_F_Tm*b_Tp_F_Tm - b_Tm_F_Tm - b_Tp_E_Tm*u**2*v - b_Tp_E_Tm*u*v**2 + b_Tp_E_Tm*u - b_Tp_E_Tm*v**3 - b_Tp_F_Tm*b_Tp_F_Tp + b_Tp_F_Tm*v + b_Tp_F_Tp + b_Tp_H_Tm*u*v - b_Tp_H_Tm*v**2',
    '-b_Tm_F_Tp*b_Tp_H_Tm - b_Tm_H_Tp - b_Tp_E_Tp*u*v + b_Tp_E_Tp*v**2 - b_Tp_F_Tp*b_Tp_H_Tp + b_Tp_F_Tp - b_Tp_H_Tp*u - b_Tp_H_Tp*v',
    '-b_Tm_F_Tm*b_Tp_H_Tm - b_Tm_H_Tm - b_Tp_E_Tm*u*v + b_Tp_E_Tm*v**2 - b_Tp_F_Tm*b_Tp_H_Tp + b_Tp_F_Tm - b_Tp_H_Tm*u - b_Tp_H_Tm*v + b_Tp_H_Tp',
    '-b_Tm_Tp_E*b_Tp_F_Tm + b_Tp_F_Tp - u',
    '-b_Tm_Tp_F*b_Tp_F_Tm + u - v',
    '-b_Tm_Tp_H*b_Tp_F_Tm + b_Tp_F_Tm - u**2 - u*v - v**2 - 1',
    '-b_Tm_F_Tm*b_Tm_Tp_E + b_Tm_F_Tp + b_Tm_Tp_E*u - b_Tm_Tp_F*u**2*v - b_Tm_Tp_F*u*v**2 + b_Tm_Tp_F*u - b_Tm_Tp_F*v**3 - b_Tm_Tp_H*u*v + b_Tm_Tp_H*v**2 + u*v - v**2',
    '-b_Tm_F_Tm*b_Tm_Tp_F - b_Tm_Tp_E*u + b_Tm_Tp_E*v + b_Tm_Tp_F*v + b_Tm_Tp_H',
    '-b_Tm_F_Tm*b_Tm_Tp_H + b_Tm_F_Tm + b_Tm_Tp_E*u**2 + b_Tm_Tp_E*u*v + b_Tm_Tp_E*v**2 + b_Tm_Tp_F*u*v - b_Tm_Tp_F*v**2 - b_Tm_Tp_H*u - b_Tm_Tp_H*v + u + v',
    '-b_Tm_E_Tm*b_Tm_F_Tp - b_Tm_E_Tp*b_Tp_F_Tp + b_Tm_E_Tp*u - b_Tm_F_Tp*u + b_Tm_F_Tp*v + b_Tm_H_Tp*u**2 + b_Tm_H_Tp*u*v + b_Tm_H_Tp*v**2',
    '-b_Tm_E_Tm*b_Tm_F_Tm + b_Tm_E_Tm*u - b_Tm_E_Tp*b_Tp_F_Tm + b_Tm_E_Tp - b_Tm_F_Tm*u + b_Tm_F_Tm*v + b_Tm_H_Tm*u**2 + b_Tm_H_Tm*u*v + b_Tm_H_Tm*v**2',
    '-b_Tm_E_Tp*u**2*v - b_Tm_E_Tp*u*v**2 + b_Tm_E_Tp*u - b_Tm_E_Tp*v**3 - b_Tm_F_Tm*b_Tm_F_Tp - b_Tm_F_Tp*b_Tp_F_Tp + b_Tm_F_Tp*v + b_Tm_H_Tp*u*v - b_Tm_H_Tp*v**2',
    '-b_Tm_E_Tm*u**2*v - b_Tm_E_Tm*u*v**2 + b_Tm_E_Tm*u - b_Tm_E_Tm*v**3 - b_Tm_F_Tm**2 + b_Tm_F_Tm*v - b_Tm_F_Tp*b_Tp_F_Tm + b_Tm_F_Tp + b_Tm_H_Tm*u*v - b_Tm_H_Tm*v**2',
    '-b_Tm_E_Tp*u*v + b_Tm_E_Tp*v**2 - b_Tm_F_Tp*b_Tm_H_Tm + b_Tm_F_Tp - b_Tm_H_Tp*b_Tp_F_Tp - b_Tm_H_Tp*u - b_Tm_H_Tp*v',
    '-b_Tm_E_Tm*u*v + b_Tm_E_Tm*v**2 - b_Tm_F_Tm*b_Tm_H_Tm + b_Tm_F_Tm - b_Tm_H_Tm*u - b_Tm_H_Tm*v - b_Tm_H_Tp*b_Tp_F_Tm + b_Tm_H_Tp',
    'b_Tm_Tp_E*b_Tp_F_Tp - b_Tm_Tp_E*u + b_Tm_Tp_F*u**2*v + b_Tm_Tp_F*u*v**2 - b_Tm_Tp_F*u + b_Tm_Tp_F*v**3 + b_Tm_Tp_H*u*v - b_Tm_Tp_H*v**2',
    'b_Tm_Tp_E*u - b_Tm_Tp_E*v + b_Tm_Tp_F*b_Tp_F_Tp - b_Tm_Tp_F*v - b_Tm_Tp_H - b_Tp_F_Tm + 1',
    '-b_Tm_Tp_E*u**2 - b_Tm_Tp_E*u*v - b_Tm_Tp_E*v**2 - b_Tm_Tp_F*u*v + b_Tm_Tp_F*v**2 + b_Tm_Tp_H*b_Tp_F_Tp + b_Tm_Tp_H*u + b_Tm_Tp_H*v',
    'b_Tm_F_Tp*b_Tm_Tp_E - u**2*v - u*v**2 + u - v**3',
    '-b_Tm_F_Tm + b_Tm_F_Tp*b_Tm_Tp_F + v',
    'b_Tm_F_Tp*b_Tm_Tp_H + u*v - v**2',
    'b_Tm_E_Tp*b_Tp_H_Tm - b_Tm_H_Tp*b_Tp_E_Tm - b_Tp_E_Tp - b_Tp_H_Tm',
    'b_Tm_E_Tm*b_Tp_H_Tm - b_Tm_H_Tm*b_Tp_E_Tm + b_Tp_E_Tm*b_Tp_H_Tp + b_Tp_E_Tm - b_Tp_E_Tp*b_Tp_H_Tm',
    '-b_Tm_E_Tm*b_Tm_H_Tp + b_Tm_E_Tp*b_Tm_H_Tm - b_Tm_E_Tp*b_Tp_H_Tp - b_Tm_H_Tm + b_Tm_H_Tp*b_Tp_E_Tp + b_Tp_H_Tp',
    '-b_Tm_E_Tm - b_Tm_E_Tp*b_Tp_H_Tm + b_Tm_H_Tp*b_Tp_E_Tm + b_Tp_H_Tm',
    'b_Tm_F_Tp*b_Tp_H_Tm - b_Tm_H_Tp*b_Tp_F_Tm + b_Tm_H_Tp + b_Tp_F_Tp',
    'b_Tm_F_Tm*b_Tp_H_Tm - b_Tm_H_Tm*b_Tp_F_Tm + b_Tm_H_Tm + b_Tp_F_Tm*b_Tp_H_Tp - b_Tp_F_Tp*b_Tp_H_Tm - b_Tp_H_Tp',
    '-b_Tm_F_Tm*b_Tm_H_Tp + b_Tm_F_Tp*b_Tm_H_Tm - b_Tm_F_Tp*b_Tp_H_Tp - b_Tm_F_Tp + b_Tm_H_Tp*b_Tp_F_Tp',
    'b_Tm_F_Tm - b_Tm_F_Tp*b_Tp_H_Tm + b_Tm_H_Tp*b_Tp_F_Tm - b_Tm_H_Tp',
    '-b_Tm_H_Tp*b_Tp_E_Tm - b_Tp_E_Tp*b_Tp_H_Tp - b_Tp_F_Tp + b_Tp_H_Tp*u - b_Tp_H_Tp*v',
    '-b_Tm_H_Tm*b_Tp_E_Tm - b_Tp_E_Tm - b_Tp_E_Tp*b_Tp_H_Tm - b_Tp_F_Tm + b_Tp_H_Tm*u - b_Tp_H_Tm*v',
    '-b_Tm_H_Tp*b_Tp_F_Tm - b_Tp_E_Tp*u*v + b_Tp_E_Tp*v**2 - b_Tp_F_Tp*b_Tp_H_Tp - b_Tp_F_Tp - b_Tp_H_Tp*u - b_Tp_H_Tp*v',
    '-b_Tm_H_Tm*b_Tp_F_Tm - b_Tp_E_Tm*u*v + b_Tp_E_Tm*v**2 + b_Tp_F_Tm - b_Tp_F_Tp*b_Tp_H_Tm - b_Tp_H_Tm*u - b_Tp_H_Tm*v',
    '-b_Tm_H_Tp*b_Tp_H_Tm - b_Tp_E_Tp*v - b_Tp_H_Tp**2 + b_Tp_H_Tp',
    '-b_Tm_H_Tm*b_Tp_H_Tm - b_Tp_E_Tm*v - b_Tp_H_Tm*b_Tp_H_Tp',
    '-b_Tm_Tp_E*b_Tp_H_Tm + b_Tp_H_Tp - 1',
    '-b_Tm_Tp_F*b_Tp_H_Tm + 1',
    '-b_Tm_Tp_H*b_Tp_H_Tm + b_Tp_H_Tm - u + v',
    '-b_Tm_H_Tm*b_Tm_Tp_E + b_Tm_H_Tp - b_Tm_Tp_F*u*v + b_Tm_Tp_F*v**2 - b_Tm_Tp_H*v + v',
    '-b_Tm_H_Tm*b_Tm_Tp_F - b_Tm_Tp_E - b_Tm_Tp_F',
    '-b_Tm_H_Tm*b_Tm_Tp_H + b_Tm_H_Tm + b_Tm_Tp_E*u - b_Tm_Tp_E*v - b_Tm_Tp_F*u - b_Tm_Tp_F*v + b_Tm_Tp_H - 1',
    '-b_Tm_E_Tm*b_Tm_H_Tp - b_Tm_E_Tp*b_Tp_H_Tp + b_Tm_E_Tp - b_Tm_F_Tp + b_Tm_H_Tp*u - b_Tm_H_Tp*v',
    '-b_Tm_E_Tm*b_Tm_H_Tm - b_Tm_E_Tp*b_Tp_H_Tm - b_Tm_F_Tm + b_Tm_H_Tm*u - b_Tm_H_Tm*v',
    '-b_Tm_E_Tp*u*v + b_Tm_E_Tp*v**2 - b_Tm_F_Tm*b_Tm_H_Tp - b_Tm_F_Tp*b_Tp_H_Tp - b_Tm_H_Tp*u - b_Tm_H_Tp*v',
    '-b_Tm_E_Tm*u*v + b_Tm_E_Tm*v**2 - b_Tm_F_Tm*b_Tm_H_Tm - b_Tm_F_Tm - b_Tm_F_Tp*b_Tp_H_Tm - b_Tm_H_Tm*u - b_Tm_H_Tm*v',
    '-b_Tm_E_Tp*v - b_Tm_H_Tm*b_Tm_H_Tp - b_Tm_H_Tp*b_Tp_H_Tp - b_Tm_H_Tp',
    '-b_Tm_E_Tm*v - b_Tm_H_Tm**2 + b_Tm_H_Tm - b_Tm_H_Tp*b_Tp_H_Tm',
    'b_Tm_Tp_E*b_Tp_H_Tp + b_Tm_Tp_F*u*v - b_Tm_Tp_F*v**2 + b_Tm_Tp_H*v',
    'b_Tm_Tp_E + b_Tm_Tp_F*b_Tp_H_Tp + b_Tm_Tp_F - b_Tp_H_Tm',
    '-b_Tm_Tp_E*u + b_Tm_Tp_E*v + b_Tm_Tp_F*u + b_Tm_Tp_F*v + b_Tm_Tp_H*b_Tp_H_Tp - b_Tm_Tp_H',
    'b_Tm_H_Tp*b_Tm_Tp_E - u*v + v**2',
    '-b_Tm_H_Tm + b_Tm_H_Tp*b_Tm_Tp_F + 1',
    'b_Tm_H_Tp*b_Tm_Tp_H - u - v',
    'b_Tm_E_Tp*b_Tp_E_Tm - b_Tp_E_Tm + b_Tp_E_Tp**2 - b_Tp_H_Tp',
    'b_Tm_E_Tm*b_Tp_E_Tm + b_Tp_E_Tm*b_Tp_E_Tp - b_Tp_H_Tm',
    'b_Tm_E_Tp*b_Tp_F_Tm + b_Tp_E_Tp*b_Tp_F_Tp - b_Tp_E_Tp*u - b_Tp_F_Tm + b_Tp_F_Tp*u - b_Tp_F_Tp*v - b_Tp_H_Tp*u**2 - b_Tp_H_Tp*u*v - b_Tp_H_Tp*v**2 - b_Tp_H_Tp',
    'b_Tm_E_Tm*b_Tp_F_Tm + b_Tp_E_Tm*b_Tp_F_Tp - b_Tp_E_Tm*u + b_Tp_F_Tm*u - b_Tp_F_Tm*v - b_Tp_H_Tm*u**2 - b_Tp_H_Tm*u*v - b_Tp_H_Tm*v**2 - b_Tp_H_Tm',
    'b_Tm_E_Tp*b_Tp_H_Tm + b_Tp_E_Tp*b_Tp_H_Tp - b_Tp_E_Tp + b_Tp_F_Tp - b_Tp_H_Tm - b_Tp_H_Tp*u + b_Tp_H_Tp*v',
    'b_Tm_E_Tm*b_Tp_H_Tm + b_Tp_E_Tm*b_Tp_H_Tp - b_Tp_E_Tm + b_Tp_F_Tm - b_Tp_H_Tm*u + b_Tp_H_Tm*v',
    'b_Tm_Tp_E*b_Tp_E_Tm - b_Tp_E_Tp',
    'b_Tm_Tp_F*b_Tp_E_Tm',
    'b_Tm_Tp_H*b_Tp_E_Tm - b_Tp_E_Tm + 1',
    'b_Tm_E_Tm*b_Tm_Tp_E - b_Tm_E_Tp - b_Tm_Tp_F*u - b_Tm_Tp_H - 1',
    'b_Tm_E_Tm*b_Tm_Tp_F + b_Tm_Tp_F*u - b_Tm_Tp_F*v + b_Tm_Tp_H - 1',
    'b_Tm_E_Tm*b_Tm_Tp_H - b_Tm_E_Tm - b_Tm_Tp_E - b_Tm_Tp_F*u**2 - b_Tm_Tp_F*u*v - b_Tm_Tp_F*v**2 - b_Tm_Tp_F - b_Tm_Tp_H*u + b_Tm_Tp_H*v + u - v',
    'b_Tm_E_Tp + b_Tm_F_Tp*b_Tp_E_Tm + b_Tp_E_Tp*b_Tp_F_Tp - b_Tp_E_Tp*u + b_Tp_F_Tp*u - b_Tp_F_Tp*v - b_Tp_H_Tp*u**2 - b_Tp_H_Tp*u*v - b_Tp_H_Tp*v**2',
    'b_Tm_E_Tm + b_Tm_F_Tm*b_Tp_E_Tm - b_Tp_E_Tm*u + b_Tp_E_Tp*b_Tp_F_Tm - b_Tp_E_Tp + b_Tp_F_Tm*u - b_Tp_F_Tm*v - b_Tp_H_Tm*u**2 - b_Tp_H_Tm*u*v - b_Tp_H_Tm*v**2',
    'b_Tm_F_Tp*b_Tp_F_Tm + b_Tm_F_Tp + b_Tp_E_Tp*u**2*v + b_Tp_E_Tp*u*v**2 - b_Tp_E_Tp*u + b_Tp_E_Tp*v**3 + b_Tp_F_Tp**2 - b_Tp_F_Tp*v - b_Tp_H_Tp*u*v + b_Tp_H_Tp*v**2',
    'b_Tm_F_Tm*b_Tp_F_Tm + b_Tm_F_Tm + b_Tp_E_Tm*u**2*v + b_Tp_E_Tm*u*v**2 - b_Tp_E_Tm*u + b_Tp_E_Tm*v**3 + b_Tp_F_Tm*b_Tp_F_Tp - b_Tp_F_Tm*v - b_Tp_F_Tp - b_Tp_H_Tm*u*v + b_Tp_H_Tm*v**2',
    'b_Tm_F_Tp*b_Tp_H_Tm + b_Tm_H_Tp + b_Tp_E_Tp*u*v - b_Tp_E_Tp*v**2 + b_Tp_F_Tp*b_Tp_H_Tp - b_Tp_F_Tp + b_Tp_H_Tp*u + b_Tp_H_Tp*v',
    'b_Tm_F_Tm*b_Tp_H_Tm + b_Tm_H_Tm + b_Tp_E_Tm*u*v - b_Tp_E_Tm*v**2 + b_Tp_F_Tm*b_Tp_H_Tp - b_Tp_F_Tm + b_Tp_H_Tm*u + b_Tp_H_Tm*v - b_Tp_H_Tp',
    'b_Tm_Tp_E*b_Tp_F_Tm - b_Tp_F_Tp + u',
    'b_Tm_Tp_F*b_Tp_F_Tm - u + v',
    'b_Tm_Tp_H*b_Tp_F_Tm - b_Tp_F_Tm + u**2 + u*v + v**2 + 1',
    'b_Tm_F_Tm*b_Tm_Tp_E - b_Tm_F_Tp - b_Tm_Tp_E*u + b_Tm_Tp_F*u**2*v + b_Tm_Tp_F*u*v**2 - b_Tm_Tp_F*u + b_Tm_Tp_F*v**3 + b_Tm_Tp_H*u*v - b_Tm_Tp_H*v**2 - u*v + v**2',
    'b_Tm_F_Tm*b_Tm_Tp_F + b_Tm_Tp_E*u - b_Tm_Tp_E*v - b_Tm_Tp_F*v - b_Tm_Tp_H',
    'b_Tm_F_Tm*b_Tm_Tp_H - b_Tm_F_Tm - b_Tm_Tp_E*u**2 - b_Tm_Tp_E*u*v - b_Tm_Tp_E*v**2 - b_Tm_Tp_F*u*v + b_Tm_Tp_F*v**2 + b_Tm_Tp_H*u + b_Tm_Tp_H*v - u - v',
    'b_Tm_H_Tp*b_Tp_E_Tm + b_Tp_E_Tp*b_Tp_H_Tp + b_Tp_F_Tp - b_Tp_H_Tp*u + b_Tp_H_Tp*v',
    'b_Tm_H_Tm*b_Tp_E_Tm + b_Tp_E_Tm + b_Tp_E_Tp*b_Tp_H_Tm + b_Tp_F_Tm - b_Tp_H_Tm*u + b_Tp_H_Tm*v',
    'b_Tm_H_Tp*b_Tp_F_Tm + b_Tp_E_Tp*u*v - b_Tp_E_Tp*v**2 + b_Tp_F_Tp*b_Tp_H_Tp + b_Tp_F_Tp + b_Tp_H_Tp*u + b_Tp_H_Tp*v',
    'b_Tm_H_Tm*b_Tp_F_Tm + b_Tp_E_Tm*u*v - b_Tp_E_Tm*v**2 - b_Tp_F_Tm + b_Tp_F_Tp*b_Tp_H_Tm + b_Tp_H_Tm*u + b_Tp_H_Tm*v',
    'b_Tm_H_Tp*b_Tp_H_Tm + b_Tp_E_Tp*v + b_Tp_H_Tp**2 - b_Tp_H_Tp',
    'b_Tm_H_Tm*b_Tp_H_Tm + b_Tp_E_Tm*v + b_Tp_H_Tm*b_Tp_H_Tp',
    'b_Tm_Tp_E*b_Tp_H_Tm - b_Tp_H_Tp + 1',
    'b_Tm_Tp_F*b_Tp_H_Tm - 1',
    'b_Tm_Tp_H*b_Tp_H_Tm - b_Tp_H_Tm + u - v',
    'b_Tm_H_Tm*b_Tm_Tp_E - b_Tm_H_Tp + b_Tm_Tp_F*u*v - b_Tm_Tp_F*v**2 + b_Tm_Tp_H*v - v',
    'b_Tm_H_Tm*b_Tm_Tp_F + b_Tm_Tp_E + b_Tm_Tp_F',
    'b_Tm_H_Tm*b_Tm_Tp_H - b_Tm_H_Tm - b_Tm_Tp_E*u + b_Tm_Tp_E*v + b_Tm_Tp_F*u + b_Tm_Tp_F*v - b_Tm_Tp_H + 1',
    '-b_Tm_Tp_E*b_Tp_E_Tm + b_Tp_E_Tp',
    '-b_Tm_Tp_F*b_Tp_E_Tm',
    '-b_Tm_Tp_H*b_Tp_E_Tm + b_Tp_E_Tm - 1',
    '-b_Tm_Tp_E*b_Tp_F_Tm + b_Tp_F_Tp - u',
    '-b_Tm_Tp_F*b_Tp_F_Tm + u - v',
    '-b_Tm_Tp_H*b_Tp_F_Tm + b_Tp_F_Tm - u**2 - u*v - v**2 - 1',
    '-b_Tm_Tp_E*b_Tp_H_Tm + b_Tp_H_Tp - 1',
    '-b_Tm_Tp_F*b_Tp_H_Tm + 1',
    '-b_Tm_Tp_H*b_Tp_H_Tm + b_Tp_H_Tm - u + v',
    '-b_Tm_E_Tp - b_Tm_Tp_E*b_Tp_E_Tp - b_Tm_Tp_F*b_Tp_F_Tp - b_Tm_Tp_H*b_Tp_H_Tp + b_Tp_H_Tp + 1',
    '-b_Tm_E_Tm - b_Tm_Tp_E*b_Tp_E_Tm - b_Tm_Tp_F*b_Tp_F_Tm - b_Tm_Tp_H*b_Tp_H_Tm + b_Tp_H_Tm',
    'b_Tm_E_Tm*b_Tm_Tp_E - b_Tm_E_Tp - b_Tm_Tp_E*b_Tp_E_Tp',
    'b_Tm_E_Tm*b_Tm_Tp_F - b_Tm_Tp_F*b_Tp_E_Tp + b_Tp_E_Tm - 1',
    'b_Tm_E_Tm*b_Tm_Tp_H - b_Tm_E_Tm - b_Tm_Tp_H*b_Tp_E_Tp + u - v',
    'b_Tm_F_Tm*b_Tm_Tp_E - b_Tm_F_Tp - b_Tm_Tp_E*b_Tp_F_Tp - u*v + v**2',
    'b_Tm_F_Tm*b_Tm_Tp_F - b_Tm_Tp_F*b_Tp_F_Tp + b_Tp_F_Tm - 1',
    'b_Tm_F_Tm*b_Tm_Tp_H - b_Tm_F_Tm - b_Tm_Tp_H*b_Tp_F_Tp - u - v',
    'b_Tm_H_Tm*b_Tm_Tp_E - b_Tm_H_Tp - b_Tm_Tp_E*b_Tp_H_Tp - v',
    'b_Tm_H_Tm*b_Tm_Tp_F - b_Tm_Tp_F*b_Tp_H_Tp + b_Tp_H_Tm',
    'b_Tm_H_Tm*b_Tm_Tp_H - b_Tm_H_Tm - b_Tm_Tp_H*b_Tp_H_Tp + 1',
    '-b_Tm_E_Tp - b_Tm_Tp_E*b_Tp_E_Tp - b_Tm_Tp_F*b_Tp_F_Tp - b_Tm_Tp_H*b_Tp_H_Tp + b_Tp_H_Tp + 1',
    '-b_Tm_E_Tm - b_Tm_Tp_E*b_Tp_E_Tm - b_Tm_Tp_F*b_Tp_F_Tm - b_Tm_Tp_H*b_Tp_H_Tm + b_Tp_H_Tm',
    'b_Tm_E_Tp*b_Tm_Tp_E + b_Tm_F_Tp*b_Tm_Tp_F + b_Tm_H_Tp*b_Tm_Tp_H + b_Tp_F_Tp',
    'b_Tm_E_Tm*b_Tm_Tp_E + b_Tm_F_Tm*b_Tm_Tp_F + b_Tm_H_Tm*b_Tm_Tp_H + b_Tp_F_Tm - 1',
    'b_Tm_E_Tm*b_Tm_E_Tp - b_Tm_E_Tm + b_Tm_E_Tp*b_Tp_E_Tp - b_Tm_H_Tp + b_Tp_E_Tp',
    'b_Tm_E_Tm**2 + b_Tm_E_Tp*b_Tp_E_Tm - b_Tm_H_Tm + b_Tp_E_Tm',
    'b_Tm_E_Tp*b_Tm_F_Tm - b_Tm_E_Tp*u - b_Tm_F_Tm + b_Tm_F_Tp*b_Tp_E_Tp + b_Tm_F_Tp*u - b_Tm_F_Tp*v - b_Tm_H_Tp*u**2 - b_Tm_H_Tp*u*v - b_Tm_H_Tp*v**2 - b_Tm_H_Tp + b_Tp_F_Tp',
    'b_Tm_E_Tm*b_Tm_F_Tm - b_Tm_E_Tm*u + b_Tm_F_Tm*u - b_Tm_F_Tm*v + b_Tm_F_Tp*b_Tp_E_Tm - b_Tm_H_Tm*u**2 - b_Tm_H_Tm*u*v - b_Tm_H_Tm*v**2 - b_Tm_H_Tm + b_Tp_F_Tm',
    'b_Tm_E_Tp*b_Tm_H_Tm - b_Tm_E_Tp + b_Tm_F_Tp - b_Tm_H_Tm + b_Tm_H_Tp*b_Tp_E_Tp - b_Tm_H_Tp*u + b_Tm_H_Tp*v + b_Tp_H_Tp',
    'b_Tm_E_Tm*b_Tm_H_Tm - b_Tm_E_Tm + b_Tm_F_Tm - b_Tm_H_Tm*u + b_Tm_H_Tm*v + b_Tm_H_Tp*b_Tp_E_Tm + b_Tp_H_Tm',
    '-b_Tm_Tp_E*b_Tp_E_Tp + b_Tm_Tp_F*u + b_Tm_Tp_H + 1',
    '-b_Tm_Tp_F*b_Tp_E_Tp - b_Tm_Tp_F*u + b_Tm_Tp_F*v - b_Tm_Tp_H + b_Tp_E_Tm',
    'b_Tm_Tp_E + b_Tm_Tp_F*u**2 + b_Tm_Tp_F*u*v + b_Tm_Tp_F*v**2 + b_Tm_Tp_F - b_Tm_Tp_H*b_Tp_E_Tp + b_Tm_Tp_H*u - b_Tm_Tp_H*v',
    '-b_Tm_E_Tp*b_Tm_Tp_E - u',
    'b_Tm_E_Tm - b_Tm_E_Tp*b_Tm_Tp_F + u - v',
    '-b_Tm_E_Tp*b_Tm_Tp_H - u**2 - u*v - v**2',
    'b_Tm_E_Tm*b_Tm_F_Tp + b_Tm_E_Tp*b_Tp_F_Tp - b_Tm_E_Tp*u + b_Tm_F_Tp*u - b_Tm_F_Tp*v - b_Tm_H_Tp*u**2 - b_Tm_H_Tp*u*v - b_Tm_H_Tp*v**2',
    'b_Tm_E_Tm*b_Tm_F_Tm - b_Tm_E_Tm*u + b_Tm_E_Tp*b_Tp_F_Tm - b_Tm_E_Tp + b_Tm_F_Tm*u - b_Tm_F_Tm*v - b_Tm_H_Tm*u**2 - b_Tm_H_Tm*u*v - b_Tm_H_Tm*v**2',
    'b_Tm_E_Tp*u**2*v + b_Tm_E_Tp*u*v**2 - b_Tm_E_Tp*u + b_Tm_E_Tp*v**3 + b_Tm_F_Tm*b_Tm_F_Tp + b_Tm_F_Tp*b_Tp_F_Tp - b_Tm_F_Tp*v - b_Tm_H_Tp*u*v + b_Tm_H_Tp*v**2',
    'b_Tm_E_Tm*u**2*v + b_Tm_E_Tm*u*v**2 - b_Tm_E_Tm*u + b_Tm_E_Tm*v**3 + b_Tm_F_Tm**2 - b_Tm_F_Tm*v + b_Tm_F_Tp*b_Tp_F_Tm - b_Tm_F_Tp - b_Tm_H_Tm*u*v + b_Tm_H_Tm*v**2',
    'b_Tm_E_Tp*u*v - b_Tm_E_Tp*v**2 + b_Tm_F_Tp*b_Tm_H_Tm - b_Tm_F_Tp + b_Tm_H_Tp*b_Tp_F_Tp + b_Tm_H_Tp*u + b_Tm_H_Tp*v',
    'b_Tm_E_Tm*u*v - b_Tm_E_Tm*v**2 + b_Tm_F_Tm*b_Tm_H_Tm - b_Tm_F_Tm + b_Tm_H_Tm*u + b_Tm_H_Tm*v + b_Tm_H_Tp*b_Tp_F_Tm - b_Tm_H_Tp',
    '-b_Tm_Tp_E*b_Tp_F_Tp + b_Tm_Tp_E*u - b_Tm_Tp_F*u**2*v - b_Tm_Tp_F*u*v**2 + b_Tm_Tp_F*u - b_Tm_Tp_F*v**3 - b_Tm_Tp_H*u*v + b_Tm_Tp_H*v**2',
    '-b_Tm_Tp_E*u + b_Tm_Tp_E*v - b_Tm_Tp_F*b_Tp_F_Tp + b_Tm_Tp_F*v + b_Tm_Tp_H + b_Tp_F_Tm - 1',
    'b_Tm_Tp_E*u**2 + b_Tm_Tp_E*u*v + b_Tm_Tp_E*v**2 + b_Tm_Tp_F*u*v - b_Tm_Tp_F*v**2 - b_Tm_Tp_H*b_Tp_F_Tp - b_Tm_Tp_H*u - b_Tm_Tp_H*v',
    '-b_Tm_F_Tp*b_Tm_Tp_E + u**2*v + u*v**2 - u + v**3',
    'b_Tm_F_Tm - b_Tm_F_Tp*b_Tm_Tp_F - v',
    '-b_Tm_F_Tp*b_Tm_Tp_H - u*v + v**2',
    'b_Tm_E_Tm*b_Tm_H_Tp + b_Tm_E_Tp*b_Tp_H_Tp - b_Tm_E_Tp + b_Tm_F_Tp - b_Tm_H_Tp*u + b_Tm_H_Tp*v',
    'b_Tm_E_Tm*b_Tm_H_Tm + b_Tm_E_Tp*b_Tp_H_Tm + b_Tm_F_Tm - b_Tm_H_Tm*u + b_Tm_H_Tm*v',
    'b_Tm_E_Tp*u*v - b_Tm_E_Tp*v**2 + b_Tm_F_Tm*b_Tm_H_Tp + b_Tm_F_Tp*b_Tp_H_Tp + b_Tm_H_Tp*u + b_Tm_H_Tp*v',
    'b_Tm_E_Tm*u*v - b_Tm_E_Tm*v**2 + b_Tm_F_Tm*b_Tm_H_Tm + b_Tm_F_Tm + b_Tm_F_Tp*b_Tp_H_Tm + b_Tm_H_Tm*u + b_Tm_H_Tm*v',
    'b_Tm_E_Tp*v + b_Tm_H_Tm*b_Tm_H_Tp + b_Tm_H_Tp*b_Tp_H_Tp + b_Tm_H_Tp',
    'b_Tm_E_Tm*v + b_Tm_H_Tm**2 - b_Tm_H_Tm + b_Tm_H_Tp*b_Tp_H_Tm',
    '-b_Tm_Tp_E*b_Tp_H_Tp - b_Tm_Tp_F*u*v + b_Tm_Tp_F*v**2 - b_Tm_Tp_H*v',
    '-b_Tm_Tp_E - b_Tm_Tp_F*b_Tp_H_Tp - b_Tm_Tp_F + b_Tp_H_Tm',
    'b_Tm_Tp_E*u - b_Tm_Tp_E*v - b_Tm_Tp_F*u - b_Tm_Tp_F*v - b_Tm_Tp_H*b_Tp_H_Tp + b_Tm_Tp_H',
    '-b_Tm_H_Tp*b_Tm_Tp_E + u*v - v**2',
    'b_Tm_H_Tm - b_Tm_H_Tp*b_Tm_Tp_F - 1',
    '-b_Tm_H_Tp*b_Tm_Tp_H + u + v',
    'b_Tm_E_Tp*b_Tm_Tp_E + u',
    '-b_Tm_E_Tm + b_Tm_E_Tp*b_Tm_Tp_F - u + v',
    'b_Tm_E_Tp*b_Tm_Tp_H + u**2 + u*v + v**2',
    'b_Tm_F_Tp*b_Tm_Tp_E - u**2*v - u*v**2 + u - v**3',
    '-b_Tm_F_Tm + b_Tm_F_Tp*b_Tm_Tp_F + v',
    'b_Tm_F_Tp*b_Tm_Tp_H + u*v - v**2',
    'b_Tm_H_Tp*b_Tm_Tp_E - u*v + v**2',
    '-b_Tm_H_Tm + b_Tm_H_Tp*b_Tm_Tp_F + 1',
    'b_Tm_H_Tp*b_Tm_Tp_H - u - v',
    'b_Tm_E_Tp*b_Tm_Tp_E + b_Tm_F_Tp*b_Tm_Tp_F + b_Tm_H_Tp*b_Tm_Tp_H + b_Tp_F_Tp',
    'b_Tm_E_Tm*b_Tm_Tp_E + b_Tm_F_Tm*b_Tm_Tp_F + b_Tm_H_Tm*b_Tm_Tp_H + b_Tp_F_Tm - 1',
]
