# Auto-generated polynomial system for SageMath verification
# Structure version: 1

polys_raw = [
    'Integer(0)',
    'Add(Mul(Symbol('tau10'), Symbol('tau16')), Mul(Symbol('tau18'), Symbol('tau2'), Symbol('tau8')), Symbol('tau18'), Symbol('tau21'), Symbol('tau8'))',
    'Add(Mul(Symbol('tau16'), Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau16'), Symbol('tau9')), Mul(Symbol('tau17'), Symbol('tau18')), Mul(Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau18'), Symbol('tau2'), Symbol('tau7')), Symbol('tau20'), Symbol('tau7'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau10'), Symbol('tau7')), Symbol('tau12'), Mul(Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau19'), Symbol('tau8')), Mul(Symbol('tau2'), Symbol('tau8'), Symbol('tau9')), Symbol('tau9'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau16'), Symbol('tau2')), Symbol('tau11'), Mul(Symbol('tau18'), Symbol('tau2')), Mul(Symbol('tau18'), Symbol('tau8')), Mul(Symbol('tau2'), Symbol('tau8')))',
    'Integer(0)',
    'Add(Mul(Symbol('tau12'), Symbol('tau16')), Symbol('tau17'), Mul(Symbol('tau2'), Symbol('tau20'), Symbol('tau8')), Symbol('tau20'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau16')), Mul(Symbol('tau16'), Symbol('tau2'), Symbol('tau21')), Mul(Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau17'), Symbol('tau20')), Mul(Symbol('tau2'), Symbol('tau20'), Symbol('tau7')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau2'), Symbol('tau8')), Symbol('tau11'), Mul(Symbol('tau12'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau12'), Symbol('tau7')), Mul(Symbol('tau2'), Symbol('tau21')), Mul(Symbol('tau21'), Symbol('tau8')))',
    'Add(Mul(Symbol('tau12'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau20'), Symbol('tau8')), Symbol('tau7'))',
    'Add(Mul(Integer(-1), Symbol('tau16'), Symbol('tau8')), Symbol('tau16'), Mul(Pow(Symbol('tau17'), Integer(2)), Symbol('tau2')), Symbol('tau21'))',
    'Add(Mul(Integer(-1), Symbol('tau16'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau16'), Symbol('tau17')), Mul(Integer(-1), Symbol('tau16'), Symbol('tau7')), Symbol('tau20'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau10'), Symbol('tau16')), Mul(Symbol('tau17'), Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau18'), Symbol('tau2'), Symbol('tau8')), Symbol('tau18'), Symbol('tau21'))',
    'Add(Mul(Symbol('tau16'), Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau16'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau16'), Symbol('tau9')), Mul(Symbol('tau17'), Symbol('tau18'), Symbol('tau2')), Mul(Symbol('tau17'), Symbol('tau18')), Mul(Symbol('tau18'), Symbol('tau2'), Symbol('tau7')), Symbol('tau20'))',
    'Add(Mul(Symbol('tau12'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau12'), Symbol('tau16')), Mul(Symbol('tau17'), Symbol('tau2'), Symbol('tau21')), Symbol('tau17'), Mul(Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau2'), Symbol('tau20'), Symbol('tau8')), Symbol('tau20'), Mul(Symbol('tau21'), Symbol('tau5')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau11'), Symbol('tau16')), Mul(Symbol('tau16'), Symbol('tau2'), Symbol('tau21')), Symbol('tau16'), Mul(Symbol('tau17'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau17'), Symbol('tau20')), Mul(Symbol('tau18'), Symbol('tau2')), Mul(Symbol('tau2'), Symbol('tau20'), Symbol('tau7')), Mul(Symbol('tau20'), Symbol('tau5')))',
    'Add(Mul(Symbol('tau13'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau17'), Symbol('tau2')), Mul(Integer(-1), Symbol('tau17')))',
    'Mul(Symbol('tau14'), Symbol('tau16'), Symbol('tau2'))',
    'Add(Mul(Symbol('tau15'), Symbol('tau16'), Symbol('tau2')), Symbol('tau16'), Symbol('tau2'))',
    'Add(Mul(Symbol('tau13'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau13'), Symbol('tau17')), Mul(Symbol('tau13'), Symbol('tau2'), Symbol('tau7')), Symbol('tau15'), Symbol('tau8'), Integer(1))',
    'Add(Mul(Symbol('tau14'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau14'), Symbol('tau17')), Mul(Symbol('tau14'), Symbol('tau2'), Symbol('tau7')), Mul(Symbol('tau15'), Symbol('tau2')), Mul(Symbol('tau16'), Symbol('tau2')), Symbol('tau16'), Mul(Integer(-1), Symbol('tau2'), Symbol('tau6')))',
    'Add(Symbol('tau13'), Symbol('tau14'), Mul(Symbol('tau15'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau15'), Symbol('tau17')), Mul(Symbol('tau15'), Symbol('tau2'), Symbol('tau7')), Mul(Symbol('tau15'), Symbol('tau5')), Mul(Symbol('tau17'), Symbol('tau2')), Symbol('tau17'), Symbol('tau3'), Symbol('tau7'))',
    'Add(Symbol('tau12'), Mul(Symbol('tau17'), Symbol('tau2'), Symbol('tau8')), Mul(Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau2'), Symbol('tau7'), Symbol('tau8')), Symbol('tau7'))',
    'Add(Symbol('tau11'), Mul(Symbol('tau16'), Symbol('tau2'), Symbol('tau8')), Mul(Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau2'), Pow(Symbol('tau7'), Integer(2))))',
    'Add(Mul(Symbol('tau10'), Symbol('tau17'), Symbol('tau2')), Symbol('tau12'), Mul(Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau2'), Symbol('tau8'), Symbol('tau9')), Symbol('tau9'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau16'), Symbol('tau2')), Symbol('tau11'), Mul(Symbol('tau18'), Symbol('tau2')), Mul(Symbol('tau2'), Symbol('tau7'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau2')), Mul(Symbol('tau11'), Symbol('tau2'), Symbol('tau8')), Symbol('tau11'), Mul(Symbol('tau12'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau12'), Symbol('tau5')), Mul(Symbol('tau2'), Symbol('tau21')), Symbol('tau8'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau2'), Symbol('tau7')), Mul(Symbol('tau11'), Symbol('tau5')), Mul(Symbol('tau12'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau2'), Symbol('tau9')), Symbol('tau7'))',
    'Add(Mul(Symbol('tau13'), Symbol('tau17')), Mul(Symbol('tau15'), Symbol('tau2')), Symbol('tau2'))',
    'Add(Mul(Symbol('tau14'), Symbol('tau17')), Mul(Symbol('tau14'), Symbol('tau5')), Symbol('tau15'), Mul(Symbol('tau16'), Symbol('tau2')))',
    'Add(Mul(Symbol('tau13'), Symbol('tau2')), Mul(Symbol('tau14'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau14'), Symbol('tau2')), Mul(Symbol('tau15'), Symbol('tau17')))',
    'Mul(Symbol('tau13'), Symbol('tau8'))',
    'Add(Mul(Symbol('tau14'), Symbol('tau8')), Mul(Symbol('tau2'), Symbol('tau7')), Symbol('tau3'))',
    'Mul(Symbol('tau15'), Symbol('tau8'))',
    'Integer(0)',
    'Add(Mul(Symbol('tau10'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau18'), Symbol('tau2')), Mul(Symbol('tau18'), Symbol('tau8')), Mul(Symbol('tau2'), Symbol('tau21')), Mul(Symbol('tau2'), Symbol('tau8')))',
    'Add(Mul(Symbol('tau16'), Symbol('tau19')), Mul(Symbol('tau16'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau17'), Symbol('tau18'), Symbol('tau2')), Symbol('tau17'), Mul(Symbol('tau18'), Symbol('tau7')), Mul(Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau2'), Symbol('tau7')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau17')), Mul(Symbol('tau10'), Symbol('tau2'), Symbol('tau7')), Mul(Symbol('tau12'), Symbol('tau2')), Mul(Symbol('tau19'), Symbol('tau2'), Symbol('tau8')), Symbol('tau19'), Mul(Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau8'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau16')), Mul(Symbol('tau11'), Symbol('tau2')), Mul(Symbol('tau18'), Symbol('tau2'), Symbol('tau8')), Symbol('tau18'), Symbol('tau8'))',
    'Integer(0)',
    'Add(Mul(Symbol('tau10'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau12'), Symbol('tau18')), Mul(Symbol('tau12'), Symbol('tau2')), Mul(Integer(-1), Symbol('tau19')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau18')), Mul(Symbol('tau11'), Symbol('tau2')), Mul(Symbol('tau18'), Symbol('tau2'), Symbol('tau21')), Mul(Symbol('tau19'), Symbol('tau20')), Mul(Symbol('tau2'), Symbol('tau20'), Symbol('tau9')), Symbol('tau21'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau11'), Symbol('tau2')), Mul(Symbol('tau10'), Symbol('tau21')), Symbol('tau10'), Mul(Symbol('tau12'), Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau12'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau20')), Mul(Symbol('tau12'), Symbol('tau18'), Symbol('tau2')), Symbol('tau12'), Mul(Integer(-1), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau17'), Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau2'), Symbol('tau8')))',
    'Add(Mul(Symbol('tau16'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau17'), Symbol('tau18'), Symbol('tau2')), Symbol('tau17'), Mul(Symbol('tau2'), Symbol('tau7')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau18'), Symbol('tau2')), Mul(Symbol('tau10'), Symbol('tau2')), Mul(Symbol('tau17'), Pow(Symbol('tau5'), Integer(3))), Mul(Pow(Symbol('tau19'), Integer(2)), Symbol('tau2')), Mul(Symbol('tau2'), Symbol('tau21'), Pow(Symbol('tau5'), Integer(2))))',
    'Add(Mul(Symbol('tau16'), Pow(Symbol('tau5'), Integer(3))), Mul(Symbol('tau18'), Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau18'), Symbol('tau2'), Symbol('tau9')), Symbol('tau19'), Mul(Symbol('tau2'), Symbol('tau20'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau2'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau12'), Symbol('tau2')), Mul(Symbol('tau19'), Symbol('tau2'), Symbol('tau21')), Symbol('tau19'), Mul(Symbol('tau21'), Symbol('tau5')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau2')), Mul(Symbol('tau18'), Symbol('tau2'), Symbol('tau21')), Symbol('tau18'), Mul(Symbol('tau2'), Symbol('tau20'), Symbol('tau9')), Mul(Symbol('tau20'), Symbol('tau5')), Symbol('tau21'))',
    'Add(Mul(Symbol('tau13'), Symbol('tau18'), Symbol('tau2')), Symbol('tau19'))',
    'Add(Mul(Symbol('tau14'), Symbol('tau18'), Symbol('tau2')), Mul(Symbol('tau2'), Symbol('tau3')))',
    'Add(Mul(Symbol('tau15'), Symbol('tau18'), Symbol('tau2')), Symbol('tau18'), Mul(Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Symbol('tau2'))',
    'Add(Symbol('tau10'), Mul(Symbol('tau13'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau14'), Pow(Symbol('tau5'), Integer(3))), Mul(Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))))',
    'Add(Mul(Symbol('tau14'), Symbol('tau2'), Symbol('tau9')), Symbol('tau15'))',
    'Add(Mul(Symbol('tau14'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau15'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau15'), Symbol('tau5')), Mul(Symbol('tau2'), Symbol('tau4')), Symbol('tau9'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau10'), Symbol('tau17')), Mul(Symbol('tau10'), Symbol('tau2'), Symbol('tau7')), Mul(Symbol('tau19'), Symbol('tau2'), Symbol('tau8')), Mul(Symbol('tau2'), Symbol('tau8'), Symbol('tau9')), Mul(Symbol('tau8'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau10'), Symbol('tau16')), Mul(Symbol('tau18'), Symbol('tau2'), Symbol('tau8')), Mul(Symbol('tau2'), Symbol('tau7'), Symbol('tau9')), Symbol('tau8'))',
    'Add(Mul(Integer(-1), Symbol('tau10'), Symbol('tau19')), Mul(Integer(-1), Symbol('tau10'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau10'), Symbol('tau9')), Mul(Symbol('tau12'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Pow(Symbol('tau5'), Integer(3)), Symbol('tau8')))',
    'Add(Mul(Integer(-1), Symbol('tau10'), Symbol('tau18')), Symbol('tau10'), Mul(Symbol('tau11'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau2'), Pow(Symbol('tau9'), Integer(2))), Mul(Pow(Symbol('tau5'), Integer(3)), Symbol('tau7')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau11'), Symbol('tau2')), Mul(Symbol('tau10'), Symbol('tau2'), Symbol('tau21')), Mul(Symbol('tau10'), Symbol('tau21')), Symbol('tau10'), Mul(Symbol('tau12'), Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau12'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau12'), Symbol('tau5')), Mul(Symbol('tau12'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau10'), Symbol('tau20')), Mul(Symbol('tau11'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau11'), Symbol('tau5')), Mul(Symbol('tau12'), Symbol('tau18'), Symbol('tau2')), Symbol('tau12'), Symbol('tau9'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau2')), Symbol('tau10'), Mul(Symbol('tau13'), Symbol('tau19')), Mul(Symbol('tau13'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau13'), Symbol('tau9')), Mul(Symbol('tau15'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))))',
    'Add(Mul(Symbol('tau13'), Symbol('tau5')), Mul(Symbol('tau14'), Symbol('tau19')), Mul(Symbol('tau14'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau14'), Symbol('tau5')), Mul(Symbol('tau14'), Symbol('tau9')), Mul(Symbol('tau15'), Symbol('tau2')), Mul(Symbol('tau18'), Symbol('tau2')), Mul(Integer(-1), Symbol('tau2'), Symbol('tau6')))',
    'Add(Mul(Symbol('tau13'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau15'), Symbol('tau19')), Mul(Symbol('tau15'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau15'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau13')), Pow(Symbol('tau5'), Integer(3)))',
    'Add(Mul(Symbol('tau10'), Symbol('tau14')), Mul(Integer(-1), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau15')), Mul(Symbol('tau10'), Symbol('tau2')), Symbol('tau10'), Mul(Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))))',
    'Integer(0)',
    'Add(Mul(Symbol('tau12'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau20'), Symbol('tau8')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau16'), Symbol('tau21')), Symbol('tau16'), Mul(Symbol('tau17'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau20'), Symbol('tau7')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau2')), Mul(Symbol('tau11'), Symbol('tau8')), Mul(Symbol('tau12'), Symbol('tau17')), Mul(Symbol('tau12'), Symbol('tau2'), Symbol('tau7')), Mul(Symbol('tau2'), Symbol('tau21'), Symbol('tau8')), Symbol('tau21'))',
    'Add(Mul(Symbol('tau12'), Symbol('tau16')), Mul(Symbol('tau2'), Symbol('tau20'), Symbol('tau8')), Mul(Symbol('tau2'), Symbol('tau7')), Symbol('tau20'))',
    'Integer(0)',
    'Add(Mul(Symbol('tau10'), Symbol('tau20')), Mul(Symbol('tau12'), Symbol('tau18'), Symbol('tau2')), Symbol('tau12'), Symbol('tau19'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau18'), Symbol('tau2')), Symbol('tau11'), Mul(Symbol('tau18'), Symbol('tau21')), Mul(Symbol('tau19'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau2'), Symbol('tau21')), Mul(Symbol('tau20'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau11')), Mul(Symbol('tau10'), Symbol('tau2'), Symbol('tau21')), Mul(Integer(-1), Symbol('tau10')), Mul(Symbol('tau12'), Symbol('tau19')), Mul(Symbol('tau12'), Symbol('tau2'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau12'), Symbol('tau18')), Mul(Symbol('tau12'), Symbol('tau2')), Symbol('tau9'))',
    'Add(Mul(Symbol('tau12'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau17'), Symbol('tau2'), Symbol('tau21')), Mul(Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau21'), Symbol('tau5')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau16'), Symbol('tau2')), Mul(Integer(-1), Symbol('tau16')), Mul(Symbol('tau17'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau18'), Symbol('tau2')), Mul(Symbol('tau20'), Symbol('tau5')))',
    'Add(Mul(Symbol('tau12'), Symbol('tau18'), Symbol('tau2')), Mul(Symbol('tau19'), Symbol('tau2'), Symbol('tau21')), Mul(Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau21'), Symbol('tau5')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau18'), Symbol('tau2')), Symbol('tau18'), Mul(Symbol('tau19'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau20'), Symbol('tau5')))',
    'Add(Mul(Symbol('tau12'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau17'), Symbol('tau5')), Mul(Symbol('tau2'), Pow(Symbol('tau21'), Integer(2))), Symbol('tau21'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau16'), Symbol('tau5')), Mul(Symbol('tau2'), Symbol('tau20'), Symbol('tau21')))',
    'Add(Mul(Symbol('tau13'), Symbol('tau2'), Symbol('tau20')), Symbol('tau21'), Integer(-1))',
    'Add(Mul(Symbol('tau14'), Symbol('tau2'), Symbol('tau20')), Mul(Integer(-1), Symbol('tau2'), Symbol('tau6')))',
    'Add(Mul(Symbol('tau15'), Symbol('tau2'), Symbol('tau20')), Symbol('tau20'), Symbol('tau3'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau13'), Symbol('tau2')), Symbol('tau12'), Mul(Symbol('tau15'), Symbol('tau5')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau14'), Symbol('tau2')), Mul(Symbol('tau13'), Symbol('tau2')), Mul(Symbol('tau14'), Symbol('tau2')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau15'), Symbol('tau2')), Symbol('tau11'), Mul(Symbol('tau13'), Symbol('tau5')), Mul(Symbol('tau14'), Symbol('tau5')), Symbol('tau15'), Symbol('tau2'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau2')), Mul(Symbol('tau12'), Symbol('tau2'), Symbol('tau7')), Mul(Symbol('tau12'), Symbol('tau5')), Mul(Symbol('tau2'), Symbol('tau21'), Symbol('tau8')), Symbol('tau8'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau2'), Symbol('tau7')), Mul(Symbol('tau11'), Symbol('tau5')), Mul(Symbol('tau2'), Symbol('tau20'), Symbol('tau8')), Mul(Symbol('tau2'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau2'), Symbol('tau21')), Mul(Symbol('tau12'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau12'), Symbol('tau5')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau11'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau11'), Symbol('tau5')), Mul(Symbol('tau2'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau12'), Symbol('tau2')), Mul(Symbol('tau12'), Symbol('tau2'), Symbol('tau21')), Mul(Symbol('tau12'), Symbol('tau2')), Mul(Symbol('tau5'), Symbol('tau8')))',
    'Add(Mul(Pow(Symbol('tau11'), Integer(2)), Symbol('tau2')), Symbol('tau11'), Mul(Symbol('tau12'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau5'), Symbol('tau7')))',
    'Add(Mul(Symbol('tau13'), Symbol('tau21')), Mul(Symbol('tau14'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))))',
    'Add(Symbol('tau13'), Mul(Symbol('tau14'), Symbol('tau21')), Symbol('tau14'), Mul(Symbol('tau2'), Symbol('tau20')))',
    'Add(Mul(Symbol('tau15'), Symbol('tau2')), Mul(Symbol('tau15'), Symbol('tau21')))',
    'Mul(Symbol('tau12'), Symbol('tau13'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau2')), Mul(Symbol('tau12'), Symbol('tau14')), Mul(Integer(-1), Symbol('tau2'), Symbol('tau6')))',
    'Add(Mul(Symbol('tau12'), Symbol('tau15')), Symbol('tau4'))',
    'Add(Mul(Symbol('tau16'), Symbol('tau2'), Symbol('tau8')), Mul(Symbol('tau16'), Symbol('tau2')), Mul(Integer(-1), Symbol('tau16'), Symbol('tau8')), Pow(Symbol('tau17'), Integer(2)), Mul(Symbol('tau2'), Symbol('tau21')))',
    'Add(Mul(Symbol('tau16'), Symbol('tau17'), Symbol('tau2')), Mul(Integer(-1), Symbol('tau16'), Symbol('tau17')), Mul(Symbol('tau16'), Symbol('tau2'), Symbol('tau7')), Mul(Integer(-1), Symbol('tau16'), Symbol('tau7')), Mul(Symbol('tau2'), Symbol('tau20')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau10'), Symbol('tau16')), Mul(Symbol('tau17'), Symbol('tau19')), Mul(Symbol('tau18'), Symbol('tau2')), Mul(Symbol('tau18'), Symbol('tau8')), Mul(Symbol('tau19'), Symbol('tau5')), Mul(Symbol('tau2'), Symbol('tau21'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau2'), Symbol('tau21')))',
    'Add(Mul(Symbol('tau16'), Symbol('tau19')), Mul(Symbol('tau16'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau16'), Symbol('tau9')), Mul(Symbol('tau17'), Symbol('tau18'), Symbol('tau2')), Mul(Symbol('tau17'), Symbol('tau18')), Mul(Symbol('tau18'), Symbol('tau5')), Mul(Symbol('tau18'), Symbol('tau7')), Mul(Symbol('tau2'), Symbol('tau20'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau2'), Symbol('tau20')))',
    'Add(Mul(Symbol('tau12'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau12'), Symbol('tau16')), Mul(Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau17'), Symbol('tau21')), Symbol('tau19'), Mul(Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau20'), Symbol('tau8')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau11'), Symbol('tau16')), Mul(Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau16'), Symbol('tau21')), Mul(Symbol('tau17'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau17'), Symbol('tau20')), Symbol('tau18'), Mul(Symbol('tau20'), Symbol('tau7')))',
    'Add(Mul(Symbol('tau13'), Symbol('tau16')), Mul(Integer(-1), Symbol('tau17')))',
    'Mul(Symbol('tau14'), Symbol('tau16'))',
    'Add(Mul(Symbol('tau15'), Symbol('tau16')), Mul(Symbol('tau16'), Symbol('tau2')), Mul(Integer(-1), Symbol('tau2'), Symbol('tau6')))',
    'Add(Mul(Symbol('tau13'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau13'), Symbol('tau17')), Mul(Symbol('tau13'), Symbol('tau7')), Mul(Symbol('tau15'), Symbol('tau2')), Mul(Symbol('tau2'), Symbol('tau8')), Integer(-1))',
    'Add(Mul(Symbol('tau14'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau14'), Symbol('tau17')), Mul(Symbol('tau14'), Symbol('tau5')), Mul(Symbol('tau14'), Symbol('tau7')), Symbol('tau15'), Mul(Symbol('tau16'), Symbol('tau2')), Symbol('tau16'), Symbol('tau2'))',
    'Add(Mul(Symbol('tau13'), Symbol('tau2')), Mul(Symbol('tau14'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau14'), Symbol('tau2')), Mul(Symbol('tau15'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau15'), Symbol('tau17')), Mul(Symbol('tau15'), Symbol('tau7')), Mul(Symbol('tau17'), Symbol('tau2')), Symbol('tau17'), Mul(Symbol('tau2'), Symbol('tau3')), Mul(Symbol('tau2'), Symbol('tau7')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau16')), Mul(Symbol('tau17'), Symbol('tau19')), Mul(Symbol('tau19'), Symbol('tau5')), Mul(Symbol('tau2'), Symbol('tau21'), Pow(Symbol('tau5'), Integer(2))), Symbol('tau8'))',
    'Add(Mul(Symbol('tau16'), Symbol('tau9')), Mul(Symbol('tau17'), Symbol('tau18')), Mul(Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau18'), Symbol('tau5')), Mul(Symbol('tau2'), Symbol('tau20'), Pow(Symbol('tau5'), Integer(2))), Symbol('tau7'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau18')), Symbol('tau10'), Pow(Symbol('tau19'), Integer(2)), Mul(Symbol('tau19'), Symbol('tau5')))',
    'Add(Mul(Symbol('tau18'), Symbol('tau19')), Mul(Symbol('tau18'), Symbol('tau5')), Mul(Symbol('tau18'), Symbol('tau9')), Mul(Symbol('tau19'), Symbol('tau2')), Symbol('tau9'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau20')), Symbol('tau12'), Mul(Symbol('tau17'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau19'), Symbol('tau21')))',
    'Add(Symbol('tau11'), Mul(Symbol('tau16'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau18'), Symbol('tau2')), Mul(Symbol('tau18'), Symbol('tau21')), Mul(Symbol('tau2'), Symbol('tau21')), Mul(Symbol('tau20'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau13'), Symbol('tau18')), Mul(Symbol('tau19'), Symbol('tau2')))',
    'Add(Mul(Symbol('tau14'), Symbol('tau18')), Symbol('tau3'))',
    'Add(Mul(Symbol('tau15'), Symbol('tau18')), Mul(Symbol('tau18'), Symbol('tau2')), Mul(Integer(-1), Symbol('tau2'), Symbol('tau6')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau2')), Mul(Symbol('tau13'), Symbol('tau9')), Mul(Symbol('tau15'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))))',
    'Add(Mul(Symbol('tau13'), Symbol('tau5')), Mul(Symbol('tau14'), Symbol('tau5')), Mul(Symbol('tau14'), Symbol('tau9')), Mul(Symbol('tau15'), Symbol('tau2')))',
    'Add(Mul(Symbol('tau13'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau15'), Symbol('tau9')), Mul(Symbol('tau2'), Symbol('tau9')), Symbol('tau4'))',
    'Add(Mul(Symbol('tau12'), Symbol('tau16')), Mul(Symbol('tau17'), Symbol('tau21')), Symbol('tau19'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau16')), Symbol('tau16'), Mul(Symbol('tau17'), Symbol('tau20')), Symbol('tau18'))',
    'Add(Mul(Symbol('tau12'), Symbol('tau18')), Mul(Symbol('tau17'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau19'), Symbol('tau21')), Symbol('tau19'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau18')), Mul(Symbol('tau16'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau18'), Symbol('tau2')), Mul(Symbol('tau19'), Symbol('tau20')))',
    'Add(Mul(Symbol('tau12'), Symbol('tau20')), Mul(Symbol('tau2'), Symbol('tau21')), Pow(Symbol('tau21'), Integer(2)))',
    'Add(Mul(Symbol('tau11'), Symbol('tau20')), Mul(Symbol('tau20'), Symbol('tau21')))',
    'Add(Mul(Symbol('tau13'), Symbol('tau20')), Mul(Symbol('tau2'), Symbol('tau21')), Integer(1))',
    'Add(Mul(Symbol('tau14'), Symbol('tau20')), Symbol('tau2'))',
    'Add(Mul(Symbol('tau15'), Symbol('tau20')), Mul(Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau2'), Symbol('tau3')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau13')), Mul(Symbol('tau12'), Symbol('tau2')), Mul(Symbol('tau14'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Symbol('tau5'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau14')), Symbol('tau13'), Symbol('tau14'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau15')), Mul(Symbol('tau11'), Symbol('tau2')), Mul(Symbol('tau15'), Symbol('tau2')), Mul(Integer(-1), Symbol('tau2'), Symbol('tau6')))',
    'Add(Mul(Integer(-1), Symbol('tau13'), Symbol('tau16')), Symbol('tau17'))',
    'Mul(Integer(-1), Symbol('tau14'), Symbol('tau16'))',
    'Add(Mul(Integer(-1), Symbol('tau15'), Symbol('tau16')), Symbol('tau16'), Integer(-1))',
    'Add(Mul(Integer(-1), Symbol('tau13'), Symbol('tau18')), Symbol('tau19'))',
    'Mul(Integer(-1), Symbol('tau14'), Symbol('tau18'))',
    'Add(Mul(Integer(-1), Symbol('tau15'), Symbol('tau18')), Symbol('tau18'), Integer(-1))',
    'Add(Mul(Integer(-1), Symbol('tau13'), Symbol('tau20')), Symbol('tau21'), Integer(-1))',
    'Add(Mul(Integer(-1), Symbol('tau14'), Symbol('tau20')), Integer(1))',
    'Add(Mul(Integer(-1), Symbol('tau15'), Symbol('tau20')), Symbol('tau20'), Mul(Integer(-1), Symbol('tau5')))',
    'Add(Mul(Integer(-1), Symbol('tau13'), Symbol('tau17')), Mul(Integer(-1), Symbol('tau14'), Symbol('tau19')), Mul(Integer(-1), Symbol('tau15'), Symbol('tau21')), Symbol('tau21'), Mul(Integer(-1), Symbol('tau8')), Integer(1))',
    'Add(Mul(Integer(-1), Symbol('tau13'), Symbol('tau16')), Mul(Integer(-1), Symbol('tau14'), Symbol('tau18')), Mul(Integer(-1), Symbol('tau15'), Symbol('tau20')), Symbol('tau20'), Mul(Integer(-1), Symbol('tau7')))',
    'Add(Mul(Symbol('tau13'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau13'), Symbol('tau7')), Mul(Symbol('tau2'), Symbol('tau8')))',
    'Add(Mul(Symbol('tau14'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau14'), Symbol('tau7')), Symbol('tau16'), Symbol('tau2'))',
    'Add(Mul(Symbol('tau15'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau15'), Symbol('tau7')), Mul(Symbol('tau2'), Symbol('tau3')), Mul(Symbol('tau2'), Symbol('tau7')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau2')), Mul(Symbol('tau13'), Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau13'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau14'), Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau14'), Symbol('tau9')), Symbol('tau18'), Symbol('tau2'))',
    'Add(Mul(Symbol('tau15'), Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau15'), Symbol('tau9')), Mul(Symbol('tau2'), Symbol('tau9')), Symbol('tau4'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau13')), Mul(Symbol('tau12'), Symbol('tau2')), Mul(Symbol('tau13'), Symbol('tau2'), Symbol('tau21')), Symbol('tau5'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau14')), Mul(Symbol('tau14'), Symbol('tau2'), Symbol('tau21')), Symbol('tau20'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau15')), Mul(Symbol('tau11'), Symbol('tau2')), Mul(Symbol('tau15'), Symbol('tau2'), Symbol('tau21')), Mul(Integer(-1), Symbol('tau2'), Symbol('tau6')))',
    'Add(Mul(Symbol('tau13'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau14'), Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau15'), Symbol('tau2'), Symbol('tau21')), Mul(Integer(-1), Symbol('tau2'), Symbol('tau6')), Mul(Symbol('tau2'), Symbol('tau8')), Symbol('tau21'))',
    'Add(Mul(Symbol('tau13'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau14'), Symbol('tau18'), Symbol('tau2')), Mul(Symbol('tau15'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau2'), Symbol('tau7')), Symbol('tau20'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau14')), Mul(Symbol('tau12'), Symbol('tau15')), Mul(Symbol('tau13'), Symbol('tau8')), Symbol('tau19'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau15')), Mul(Symbol('tau13'), Symbol('tau7')), Mul(Symbol('tau14'), Symbol('tau9')), Symbol('tau18'), Symbol('tau2'))',
    'Add(Mul(Symbol('tau12'), Symbol('tau2')), Mul(Symbol('tau17'), Symbol('tau8')), Symbol('tau17'), Mul(Symbol('tau2'), Symbol('tau7')), Mul(Symbol('tau7'), Symbol('tau8')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau2')), Mul(Symbol('tau16'), Symbol('tau8')), Symbol('tau16'), Pow(Symbol('tau7'), Integer(2)))',
    'Add(Mul(Symbol('tau10'), Symbol('tau17')), Mul(Symbol('tau10'), Symbol('tau5')), Mul(Symbol('tau12'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau12'), Symbol('tau2')), Symbol('tau19'), Mul(Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau8'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau16')), Mul(Symbol('tau11'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau11'), Symbol('tau2')), Symbol('tau18'), Mul(Symbol('tau5'), Symbol('tau9')), Mul(Symbol('tau7'), Symbol('tau9')))',
    'Add(Symbol('tau10'), Mul(Symbol('tau11'), Symbol('tau2')), Mul(Symbol('tau11'), Symbol('tau8')), Mul(Symbol('tau12'), Symbol('tau17')), Mul(Symbol('tau2'), Symbol('tau8')), Symbol('tau21'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau7')), Mul(Symbol('tau12'), Symbol('tau16')), Mul(Symbol('tau2'), Symbol('tau7')), Symbol('tau20'), Symbol('tau9'))',
    'Add(Mul(Symbol('tau13'), Symbol('tau17'), Symbol('tau2')), Symbol('tau15'), Mul(Integer(-1), Symbol('tau2'), Symbol('tau6')))',
    'Add(Mul(Symbol('tau14'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau15'), Symbol('tau2')), Symbol('tau16'))',
    'Add(Symbol('tau13'), Symbol('tau14'), Mul(Symbol('tau15'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau15'), Symbol('tau5')))',
    'Mul(Symbol('tau13'), Symbol('tau2'), Symbol('tau8'))',
    'Add(Mul(Symbol('tau14'), Symbol('tau2'), Symbol('tau8')), Mul(Symbol('tau2'), Symbol('tau3')), Symbol('tau7'))',
    'Add(Mul(Symbol('tau15'), Symbol('tau2'), Symbol('tau8')), Mul(Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))))',
    'Add(Mul(Symbol('tau10'), Symbol('tau17'), Symbol('tau2')), Mul(Symbol('tau10'), Symbol('tau17')), Mul(Symbol('tau10'), Symbol('tau5')), Mul(Symbol('tau10'), Symbol('tau7')), Mul(Symbol('tau12'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau19'), Symbol('tau8')), Mul(Symbol('tau2'), Symbol('tau8'), Symbol('tau9')), Mul(Symbol('tau8'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau16'), Symbol('tau2')), Mul(Symbol('tau10'), Symbol('tau16')), Mul(Symbol('tau11'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau18'), Symbol('tau8')), Mul(Symbol('tau2'), Symbol('tau8')), Mul(Symbol('tau5'), Symbol('tau9')), Mul(Symbol('tau7'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau19'), Symbol('tau2')), Mul(Integer(-1), Symbol('tau10'), Symbol('tau19')), Mul(Symbol('tau10'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau10'), Symbol('tau5')), Mul(Integer(-1), Symbol('tau10'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau18'), Symbol('tau2')), Mul(Integer(-1), Symbol('tau10'), Symbol('tau18')), Mul(Symbol('tau10'), Symbol('tau2')), Mul(Symbol('tau5'), Symbol('tau9')), Pow(Symbol('tau9'), Integer(2)))',
    'Add(Mul(Symbol('tau10'), Symbol('tau11')), Mul(Symbol('tau10'), Symbol('tau2'), Symbol('tau21')), Mul(Symbol('tau10'), Symbol('tau2')), Mul(Symbol('tau10'), Symbol('tau21')), Mul(Symbol('tau12'), Symbol('tau19')), Mul(Symbol('tau12'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau12'), Symbol('tau9')), Mul(Symbol('tau2'), Pow(Symbol('tau5'), Integer(2)), Symbol('tau8')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau2'), Symbol('tau20')), Mul(Symbol('tau10'), Symbol('tau20')), Mul(Symbol('tau11'), Symbol('tau9')), Mul(Symbol('tau12'), Symbol('tau18')), Mul(Symbol('tau12'), Symbol('tau2')), Mul(Symbol('tau2'), Pow(Symbol('tau5'), Integer(2)), Symbol('tau7')), Mul(Symbol('tau2'), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau2')), Symbol('tau10'), Mul(Symbol('tau13'), Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau13'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau13'), Symbol('tau9')), Mul(Symbol('tau14'), Pow(Symbol('tau5'), Integer(3))))',
    'Add(Mul(Symbol('tau14'), Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau14'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau14'), Symbol('tau9')), Symbol('tau15'), Symbol('tau18'), Symbol('tau2'))',
    'Add(Mul(Symbol('tau14'), Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))), Mul(Symbol('tau15'), Symbol('tau19'), Symbol('tau2')), Mul(Symbol('tau15'), Symbol('tau2'), Symbol('tau9')), Mul(Symbol('tau15'), Symbol('tau5')), Mul(Symbol('tau15'), Symbol('tau9')))',
    'Mul(Symbol('tau10'), Symbol('tau13'), Symbol('tau2'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau14'), Symbol('tau2')), Mul(Symbol('tau2'), Symbol('tau9')), Symbol('tau5'), Mul(Integer(-1), Symbol('tau9')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau15'), Symbol('tau2')), Mul(Symbol('tau10'), Symbol('tau2')), Symbol('tau10'))',
    'Add(Symbol('tau10'), Mul(Symbol('tau12'), Symbol('tau7')), Mul(Symbol('tau21'), Symbol('tau8')), Mul(Integer(-1), Symbol('tau8')))',
    'Add(Mul(Symbol('tau11'), Symbol('tau7')), Mul(Symbol('tau20'), Symbol('tau8')), Symbol('tau9'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau21')), Mul(Symbol('tau12'), Symbol('tau9')), Mul(Symbol('tau2'), Pow(Symbol('tau5'), Integer(2)), Symbol('tau8')))',
    'Add(Mul(Symbol('tau10'), Symbol('tau20')), Mul(Symbol('tau11'), Symbol('tau9')), Mul(Symbol('tau2'), Pow(Symbol('tau5'), Integer(2)), Symbol('tau7')), Symbol('tau9'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau12')), Mul(Symbol('tau12'), Symbol('tau21')), Symbol('tau12'))',
    'Add(Pow(Symbol('tau11'), Integer(2)), Mul(Symbol('tau11'), Symbol('tau2')), Mul(Symbol('tau12'), Symbol('tau20')))',
    'Add(Mul(Symbol('tau13'), Symbol('tau2'), Symbol('tau21')), Mul(Symbol('tau15'), Symbol('tau5')))',
    'Add(Mul(Symbol('tau13'), Symbol('tau2')), Mul(Symbol('tau14'), Symbol('tau2'), Symbol('tau21')), Mul(Symbol('tau14'), Symbol('tau2')), Symbol('tau20'))',
    'Add(Mul(Symbol('tau13'), Symbol('tau5')), Mul(Symbol('tau14'), Symbol('tau5')), Mul(Symbol('tau15'), Symbol('tau2'), Symbol('tau21')), Symbol('tau15'))',
    'Add(Mul(Symbol('tau12'), Symbol('tau13'), Symbol('tau2')), Mul(Symbol('tau2'), Pow(Symbol('tau5'), Integer(2))))',
    'Add(Symbol('tau11'), Mul(Symbol('tau12'), Symbol('tau14'), Symbol('tau2')), Symbol('tau2'))',
    'Add(Mul(Symbol('tau12'), Symbol('tau15'), Symbol('tau2')), Mul(Symbol('tau2'), Symbol('tau4')))',
    'Mul(Symbol('tau13'), Symbol('tau8'))',
    'Add(Mul(Symbol('tau14'), Symbol('tau8')), Mul(Integer(-1), Symbol('tau5')), Mul(Integer(-1), Symbol('tau7')))',
    'Add(Mul(Symbol('tau15'), Symbol('tau8')), Pow(Symbol('tau5'), Integer(2)))',
    'Mul(Symbol('tau10'), Symbol('tau13'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau14')), Mul(Integer(-1), Symbol('tau5')), Mul(Integer(-1), Symbol('tau9')))',
    'Mul(Symbol('tau10'), Symbol('tau15'))',
    'Add(Mul(Symbol('tau12'), Symbol('tau13')), Pow(Symbol('tau5'), Integer(2)))',
    'Add(Mul(Integer(-1), Symbol('tau11')), Mul(Symbol('tau12'), Symbol('tau14')), Integer(1))',
    'Mul(Symbol('tau12'), Symbol('tau15'))',
    'Add(Mul(Symbol('tau10'), Symbol('tau14')), Mul(Symbol('tau12'), Symbol('tau15')), Mul(Symbol('tau13'), Symbol('tau8')), Symbol('tau19'))',
    'Add(Mul(Symbol('tau11'), Symbol('tau15')), Mul(Symbol('tau13'), Symbol('tau7')), Mul(Symbol('tau14'), Symbol('tau9')), Symbol('tau18'), Integer(-1))',
]
